// src/components/parts/ClassificationBadge.tsx
import { Badge } from '@/components/ui/badge';
import { Package, Wrench, Box, Pencil } from 'lucide-react';
import type { ClassificationType } from '@/types';
import { cn } from '@/lib/utils';

interface ClassificationBadgeProps {
  classification: ClassificationType | null;
  className?: string;
  showIcon?: boolean;
  size?: 'sm' | 'md';
}

const CLASSIFICATION_CONFIG: Record<ClassificationType, { label: string; icon: typeof Package; className: string }> = {
  purchased: {
    label: 'Purchased',
    icon: Package,
    className: 'bg-blue-100 text-blue-700 hover:bg-blue-200 dark:bg-blue-900 dark:text-blue-200',
  },
  manufactured: {
    label: 'Manufactured',
    icon: Wrench,
    className: 'bg-orange-100 text-orange-700 hover:bg-orange-200 dark:bg-orange-900 dark:text-orange-200',
  },
  assembly: {
    label: 'Assembly',
    icon: Box,
    className: 'bg-purple-100 text-purple-700 hover:bg-purple-200 dark:bg-purple-900 dark:text-purple-200',
  },
  modified: {
    label: 'Modified',
    icon: Pencil,
    className: 'bg-amber-100 text-amber-700 hover:bg-amber-200 dark:bg-amber-900 dark:text-amber-200',
  },
};

export function ClassificationBadge({
  classification,
  className,
  showIcon = true,
  size = 'sm',
}: ClassificationBadgeProps) {
  if (!classification) return null;

  const config = CLASSIFICATION_CONFIG[classification];
  const Icon = config.icon;
  const iconSize = size === 'sm' ? 'h-3 w-3' : 'h-3.5 w-3.5';
  const textSize = size === 'sm' ? 'text-xs' : 'text-sm';

  return (
    <Badge
      variant="outline"
      className={cn(config.className, textSize, className)}
    >
      {showIcon && <Icon className={cn(iconSize, 'mr-1')} />}
      {config.label}
    </Badge>
  );
}

// AngularBootstrap/src/app/components/parts/classification-badge.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ClassificationType } from '../../models';

@Component({
  selector: 'app-classification-badge',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="d-flex gap-2 flex-wrap">
      <span *ngIf="classification" [class]="badgeClass">
        <i *ngIf="showIcon" [class]="iconClass + ' me-1'"></i>
        {{ label }}
      </span>
      <span *ngIf="isAssembly" class="badge bg-secondary">
        <i *ngIf="showIcon" class="bi bi-boxes me-1"></i>
        Assembly
      </span>
      <span *ngIf="isModified" class="badge bg-info text-dark">
        <i *ngIf="showIcon" class="bi bi-pencil me-1"></i>
        Modified
      </span>
    </div>
  `,
  styles: [`
    .badge {
      font-size: 0.75rem;
      padding: 0.25rem 0.5rem;
      border-radius: 0.25rem;
      font-weight: 500;
    }
  `]
})
export class ClassificationBadgeComponent {
  @Input() classification: ClassificationType | null = null;
  @Input() showIcon = true;
  @Input() size: 'sm' | 'md' = 'sm';
  @Input() isAssembly = false;
  @Input() isModified = false;

  private readonly config: Record<ClassificationType, { label: string; icon: string; class: string }> = {
    purchased: {
      label: 'Purchased',
      icon: 'bi-box-seam',
      class: 'badge bg-primary'
    },
    manufactured: {
      label: 'Manufactured',
      icon: 'bi-wrench',
      class: 'badge bg-warning text-dark'
    }
  };

  get badgeClass(): string {
    if (!this.classification) return '';
    return this.config[this.classification].class;
  }

  get iconClass(): string {
    if (!this.classification) return '';
    return `bi ${this.config[this.classification].icon}`;
  }

  get label(): string {
    if (!this.classification) return '';
    return this.config[this.classification].label;
  }
}
