// src/components/picking/PrintPickList.tsx
import { useState } from 'react';
import { Printer, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import type { Order, Tool, LineItem } from '@/types';
import { formatDate } from '@/lib/utils';

interface PrintPickListProps {
  order: Order;
  tools: Tool[];
  lineItems: LineItem[];
  getPicksForTool: (toolId: string) => Map<string, number>;
  currentToolId?: string;
}

interface PrintableToolData {
  tool: Tool;
  items: {
    partNumber: string;
    description: string;
    location: string;
    qtyNeeded: number;
    qtyPicked: number;
    remaining: number;
  }[];
}

export function PrintPickList({
  order,
  tools,
  lineItems,
  getPicksForTool,
  currentToolId,
}: PrintPickListProps) {
  const [showDialog, setShowDialog] = useState(false);
  const [printMode, setPrintMode] = useState<'current' | 'all'>('current');

  const getToolData = (tool: Tool): PrintableToolData => {
    const toolPicks = getPicksForTool(tool.id);
    const items = lineItems.map((item) => {
      const picked = toolPicks.get(item.id) || 0;
      return {
        partNumber: item.part_number,
        description: item.description || '-',
        location: item.location || '-',
        qtyNeeded: item.qty_per_unit,
        qtyPicked: picked,
        remaining: item.qty_per_unit - picked,
      };
    });
    return { tool, items };
  };

  const handlePrint = () => {
    const toolsToPrint =
      printMode === 'current' && currentToolId
        ? tools.filter((t) => t.id === currentToolId)
        : tools;

    const printData = toolsToPrint.map(getToolData);

    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      alert('Please allow popups to print the pick list');
      return;
    }

    const printContent = generatePrintHTML(order, printData);
    printWindow.document.write(printContent);
    printWindow.document.close();

    // Close after printing (or after user cancels)
    printWindow.onafterprint = () => {
      printWindow.close();
    };

    setShowDialog(false);
  };

  return (
    <>
      <Button variant="outline" onClick={() => setShowDialog(true)}>
        <Printer className="h-4 w-4 mr-2" />
        Print Pick List
      </Button>

      <Dialog open={showDialog} onOpenChange={setShowDialog}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Print Pick List</DialogTitle>
          </DialogHeader>

          <div className="space-y-4 py-4">
            <p className="text-sm text-muted-foreground">
              Generate a printable pick list for this order.
            </p>

            <div className="space-y-3">
              <Label>What to print:</Label>
              <div className="space-y-2">
                {currentToolId && (
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="radio"
                      name="printMode"
                      value="current"
                      checked={printMode === 'current'}
                      onChange={() => setPrintMode('current')}
                      className="w-4 h-4"
                    />
                    <span className="text-sm">
                      Current tool only (
                      {tools.find((t) => t.id === currentToolId)?.tool_number})
                    </span>
                  </label>
                )}
                <label className="flex items-center gap-2 cursor-pointer">
                  <input
                    type="radio"
                    name="printMode"
                    value="all"
                    checked={printMode === 'all'}
                    onChange={() => setPrintMode('all')}
                    className="w-4 h-4"
                  />
                  <span className="text-sm">
                    All tools ({tools.length} tool{tools.length !== 1 ? 's' : ''})
                  </span>
                </label>
              </div>
            </div>

            <div className="bg-muted/50 rounded-lg p-3 text-sm">
              <div className="flex items-start gap-2">
                <FileText className="h-4 w-4 mt-0.5 text-muted-foreground" />
                <div>
                  <p className="font-medium">Print Preview includes:</p>
                  <ul className="mt-1 text-muted-foreground list-disc list-inside">
                    <li>Order header (SO#, Customer, PO#, Due Date)</li>
                    <li>Parts table with checkbox column</li>
                    <li>Current pick status</li>
                  </ul>
                </div>
              </div>
            </div>
          </div>

          <DialogFooter>
            <Button variant="outline" onClick={() => setShowDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handlePrint}>
              <Printer className="h-4 w-4 mr-2" />
              Print
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}

function generatePrintHTML(order: Order, toolsData: PrintableToolData[]): string {
  const toolSections = toolsData
    .map(
      ({ tool, items }) => `
      <div class="tool-section">
        <div class="tool-header">
          <h2>Tool: ${tool.tool_number}</h2>
          ${tool.serial_number ? `<span class="serial">SN: ${tool.serial_number}</span>` : ''}
        </div>

        <table class="parts-table">
          <thead>
            <tr>
              <th class="checkbox-col"></th>
              <th class="part-col">Part Number</th>
              <th class="desc-col">Description</th>
              <th class="loc-col">Location</th>
              <th class="qty-col">Needed</th>
              <th class="qty-col">Picked</th>
              <th class="qty-col">Remaining</th>
            </tr>
          </thead>
          <tbody>
            ${items
              .map(
                (item) => `
              <tr class="${item.remaining === 0 ? 'complete' : ''}">
                <td class="checkbox-col">
                  <div class="checkbox ${item.remaining === 0 ? 'checked' : ''}">
                    ${item.remaining === 0 ? '&#10003;' : ''}
                  </div>
                </td>
                <td class="part-col">${item.partNumber}</td>
                <td class="desc-col">${item.description}</td>
                <td class="loc-col">${item.location}</td>
                <td class="qty-col">${item.qtyNeeded}</td>
                <td class="qty-col">${item.qtyPicked}</td>
                <td class="qty-col ${item.remaining > 0 ? 'remaining' : ''}">${item.remaining}</td>
              </tr>
            `
              )
              .join('')}
          </tbody>
        </table>
      </div>
    `
    )
    .join('');

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <title>Pick List - SO-${order.so_number}</title>
      <style>
        * {
          box-sizing: border-box;
          margin: 0;
          padding: 0;
        }

        body {
          font-family: Arial, sans-serif;
          font-size: 12px;
          line-height: 1.4;
          padding: 20px;
          color: #333;
        }

        .header {
          border-bottom: 2px solid #333;
          padding-bottom: 15px;
          margin-bottom: 20px;
        }

        .header h1 {
          font-size: 24px;
          margin-bottom: 10px;
        }

        .header-info {
          display: grid;
          grid-template-columns: repeat(4, 1fr);
          gap: 10px;
        }

        .header-info .info-item {
          padding: 5px 0;
        }

        .header-info .label {
          font-size: 10px;
          color: #666;
          text-transform: uppercase;
        }

        .header-info .value {
          font-weight: bold;
        }

        .tool-section {
          margin-bottom: 30px;
          page-break-inside: avoid;
        }

        .tool-header {
          background: #f5f5f5;
          padding: 10px;
          margin-bottom: 10px;
          border-radius: 4px;
          display: flex;
          justify-content: space-between;
          align-items: center;
        }

        .tool-header h2 {
          font-size: 16px;
        }

        .tool-header .serial {
          color: #666;
          font-size: 11px;
        }

        .parts-table {
          width: 100%;
          border-collapse: collapse;
          font-size: 11px;
        }

        .parts-table th,
        .parts-table td {
          border: 1px solid #ddd;
          padding: 6px 8px;
          text-align: left;
        }

        .parts-table th {
          background: #f9f9f9;
          font-weight: bold;
          text-transform: uppercase;
          font-size: 10px;
        }

        .parts-table tbody tr:nth-child(even) {
          background: #fafafa;
        }

        .parts-table tbody tr.complete {
          background: #f0fff0;
        }

        .checkbox-col {
          width: 30px;
          text-align: center !important;
        }

        .checkbox {
          width: 16px;
          height: 16px;
          border: 2px solid #333;
          display: inline-flex;
          align-items: center;
          justify-content: center;
          font-size: 12px;
        }

        .checkbox.checked {
          background: #333;
          color: white;
        }

        .part-col {
          width: 150px;
          font-family: monospace;
          font-weight: bold;
        }

        .desc-col {
          min-width: 180px;
        }

        .loc-col {
          width: 100px;
        }

        .qty-col {
          width: 70px;
          text-align: center !important;
        }

        .remaining {
          font-weight: bold;
          color: #c00;
        }

        .footer {
          margin-top: 30px;
          padding-top: 15px;
          border-top: 1px solid #ddd;
          display: flex;
          justify-content: space-between;
          font-size: 10px;
          color: #666;
        }

        .signature-line {
          margin-top: 40px;
          display: flex;
          gap: 40px;
        }

        .signature-box {
          flex: 1;
        }

        .signature-box .line {
          border-bottom: 1px solid #333;
          margin-bottom: 5px;
          height: 30px;
        }

        .signature-box .label {
          font-size: 10px;
          color: #666;
        }

        @media print {
          body {
            padding: 10px;
          }

          .tool-section {
            page-break-inside: avoid;
          }

          @page {
            margin: 0.5in;
          }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1>Pick List - SO-${order.so_number}</h1>
        ${order.tool_model ? `<div style="font-size: 14px; color: #666; margin-bottom: 10px;">Model: ${order.tool_model}</div>` : ''}

        <div class="header-info">
          <div class="info-item">
            <div class="label">Customer</div>
            <div class="value">${order.customer_name || '-'}</div>
          </div>
          <div class="info-item">
            <div class="label">PO Number</div>
            <div class="value">${order.po_number || '-'}</div>
          </div>
          <div class="info-item">
            <div class="label">Order Date</div>
            <div class="value">${formatDate(order.order_date)}</div>
          </div>
          <div class="info-item">
            <div class="label">Due Date</div>
            <div class="value">${formatDate(order.due_date)}</div>
          </div>
        </div>

        ${order.notes ? `<div style="margin-top: 10px; font-style: italic; color: #666;">Notes: ${order.notes}</div>` : ''}
      </div>

      ${toolSections}

      <div class="signature-line">
        <div class="signature-box">
          <div class="line"></div>
          <div class="label">Picked By</div>
        </div>
        <div class="signature-box">
          <div class="line"></div>
          <div class="label">Date</div>
        </div>
        <div class="signature-box">
          <div class="line"></div>
          <div class="label">Verified By</div>
        </div>
      </div>

      <div class="footer">
        <span>Generated: ${new Date().toLocaleString()}</span>
        <span>Tool Pick List Tracker</span>
      </div>
      <script>
        // Print once content is fully rendered
        requestAnimationFrame(function() {
          requestAnimationFrame(function() {
            window.print();
          });
        });
      </script>
    </body>
    </html>
  `;
}

// src/app/components/picking/print-pick-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Order, Tool, LineItemWithPicks } from '../../models';

@Component({
  selector: 'app-print-pick-list',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="modal fade" [class.show]="show" [style.display]="show ? 'block' : 'none'" tabindex="-1">
      <div class="modal-dialog modal-lg">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">
              <i class="bi bi-printer me-2"></i>Print Pick List
            </h5>
            <button type="button" class="btn-close" (click)="close()"></button>
          </div>
          <div class="modal-body">
            <!-- Print Options -->
            <div class="row mb-4">
              <div class="col-md-6">
                <label class="form-label">Select Tools to Include</label>
                <div class="border rounded p-2" style="max-height: 150px; overflow-y: auto;">
                  <div class="form-check" *ngFor="let tool of tools">
                    <input
                      class="form-check-input"
                      type="checkbox"
                      [id]="'tool-' + tool.id"
                      [checked]="selectedTools.has(tool.id)"
                      (change)="toggleTool(tool.id)"
                    >
                    <label class="form-check-label" [for]="'tool-' + tool.id">
                      {{ tool.tool_number }}
                      <span class="text-muted small" *ngIf="tool.serial_number">({{ tool.serial_number }})</span>
                    </label>
                  </div>
                </div>
                <div class="mt-2">
                  <button class="btn btn-sm btn-outline-secondary me-1" (click)="selectAllTools()">Select All</button>
                  <button class="btn btn-sm btn-outline-secondary" (click)="clearToolSelection()">Clear</button>
                </div>
              </div>
              <div class="col-md-6">
                <label class="form-label">Options</label>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" id="showCompleted" [(ngModel)]="showCompleted">
                  <label class="form-check-label" for="showCompleted">Include completed items</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" id="showLocation" [(ngModel)]="showLocation">
                  <label class="form-check-label" for="showLocation">Show location column</label>
                </div>
                <div class="form-check">
                  <input class="form-check-input" type="checkbox" id="groupByLocation" [(ngModel)]="groupByLocation">
                  <label class="form-check-label" for="groupByLocation">Group by location</label>
                </div>
              </div>
            </div>

            <!-- Print Preview -->
            <div class="border rounded p-3 bg-body" id="printPreview">
              <div class="text-center mb-3">
                <h4 class="mb-1">Pick List - SO-{{ order?.so_number }}</h4>
                <p class="text-muted small mb-0">
                  {{ order?.customer_name || 'No customer' }}
                  <span *ngIf="order?.po_number"> | PO: {{ order?.po_number }}</span>
                  <span *ngIf="order?.due_date"> | Due: {{ formatDate(order?.due_date) }}</span>
                </p>
                <p class="small text-muted">
                  Tools: {{ getSelectedToolNumbers().join(', ') || 'None selected' }}
                </p>
              </div>

              <table class="table table-sm table-bordered">
                <thead class="table-secondary">
                  <tr>
                    <th style="width: 30px;"></th>
                    <th>Part Number</th>
                    <th *ngIf="showLocation">Location</th>
                    <th>Description</th>
                    <th class="text-center" style="width: 80px;">Qty</th>
                    <th class="text-center" style="width: 80px;">Picked</th>
                  </tr>
                </thead>
                <tbody>
                  <ng-container *ngFor="let item of filteredItems; let i = index">
                    <tr *ngIf="groupByLocation && shouldShowGroupHeader(item, i)" class="table-secondary">
                      <td colspan="6" class="fw-bold small py-1">
                        <i class="bi bi-geo-alt me-1"></i>{{ getLocationGroup(item.location) }}
                      </td>
                    </tr>
                    <tr>
                      <td class="text-center">
                        <div class="border rounded" style="width: 20px; height: 20px;"></div>
                      </td>
                      <td class="font-monospace small">{{ item.part_number }}</td>
                      <td *ngIf="showLocation" class="small">{{ item.location || '-' }}</td>
                      <td class="small text-muted">{{ item.description || '-' }}</td>
                      <td class="text-center fw-bold">{{ item.qty_per_unit }}</td>
                      <td class="text-center">
                        <span *ngIf="item.total_picked > 0" class="text-success">{{ item.total_picked }}</span>
                        <span *ngIf="item.total_picked === 0">-</span>
                      </td>
                    </tr>
                  </ng-container>
                </tbody>
              </table>

              <div class="row mt-4 small text-muted">
                <div class="col-6">
                  <p class="mb-1"><strong>Picked By:</strong> _____________________</p>
                </div>
                <div class="col-6 text-end">
                  <p class="mb-1"><strong>Date:</strong> _____________________</p>
                </div>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" (click)="close()">Cancel</button>
            <button type="button" class="btn btn-primary" (click)="print()">
              <i class="bi bi-printer me-1"></i> Print
            </button>
          </div>
        </div>
      </div>
    </div>
    <div class="modal-backdrop fade show" *ngIf="show"></div>
  `,
  styles: [`
    @media print {
      /* Hide modal chrome */
      .modal-header, .modal-footer, .modal-backdrop, .btn, .border, .bg-light {
        display: none !important;
      }

      /* Reset modal positioning */
      .modal, .modal-dialog, .modal-content {
        position: static !important;
        display: block !important;
        width: 100% !important;
        max-width: none !important;
        margin: 0 !important;
        padding: 0 !important;
        border: none !important;
        box-shadow: none !important;
      }

      /* Print preview becomes the full page */
      #printPreview {
        border: none !important;
        padding: 0.5in !important;
        background: white !important;
      }

      /* Clean table styling */
      .table {
        font-size: 10pt;
        width: 100%;
        border-collapse: collapse;
      }

      .table th,
      .table td {
        padding: 6px 8px;
        border: 1px solid #333;
      }

      .table thead th {
        background-color: #f0f0f0 !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
        font-weight: bold;
        border-bottom: 2px solid #000;
      }

      /* Location group headers */
      .table-secondary td {
        background-color: #e8e8e8 !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
        font-weight: bold;
        border-top: 2px solid #000;
        border-bottom: 1px solid #000;
      }

      /* Page breaks */
      .table tbody tr {
        page-break-inside: avoid;
      }

      .table-secondary {
        page-break-after: avoid;
      }

      /* Header */
      h4 {
        margin-bottom: 0.2in;
        font-size: 16pt;
      }

      /* Footer signature area */
      .row.mt-4 {
        margin-top: 0.4in !important;
        page-break-inside: avoid;
      }

      /* Checkbox squares */
      .border.rounded {
        border: 1.5px solid #000 !important;
        border-radius: 0 !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }

      /* Ensure black text */
      body, p, span, td, th {
        color: #000 !important;
      }

      .text-muted {
        color: #555 !important;
      }

      .text-success {
        color: #28a745 !important;
        -webkit-print-color-adjust: exact;
        print-color-adjust: exact;
      }
    }
  `]
})
export class PrintPickListComponent implements OnInit {
  @Input() show = false;
  @Input() order: Order | null = null;
  @Input() tools: Tool[] = [];
  @Input() lineItems: LineItemWithPicks[] = [];

  selectedTools = new Set<string>();
  showCompleted = false;
  showLocation = true;
  groupByLocation = true;

  private closeCallback: (() => void) | null = null;

  ngOnInit(): void {
    // Select all tools by default
    this.selectAllTools();
  }

  setCloseCallback(callback: () => void): void {
    this.closeCallback = callback;
  }

  close(): void {
    this.show = false;
    if (this.closeCallback) {
      this.closeCallback();
    }
  }

  toggleTool(toolId: string): void {
    if (this.selectedTools.has(toolId)) {
      this.selectedTools.delete(toolId);
    } else {
      this.selectedTools.add(toolId);
    }
  }

  selectAllTools(): void {
    this.selectedTools = new Set(this.tools.map(t => t.id));
  }

  clearToolSelection(): void {
    this.selectedTools.clear();
  }

  getSelectedToolNumbers(): string[] {
    return this.tools
      .filter(t => this.selectedTools.has(t.id))
      .map(t => t.tool_number);
  }

  get filteredItems(): LineItemWithPicks[] {
    let items = this.lineItems;

    // Filter by completion status
    if (!this.showCompleted) {
      items = items.filter(item => item.remaining > 0);
    }

    // Sort by location if grouping
    if (this.groupByLocation) {
      items = [...items].sort((a, b) => {
        const locA = a.location || '';
        const locB = b.location || '';
        if (!locA && locB) return 1;
        if (locA && !locB) return -1;
        return locA.localeCompare(locB, undefined, { numeric: true });
      });
    }

    return items;
  }

  getLocationGroup(location: string | null | undefined): string {
    if (!location) return 'No Location';
    const parts = location.split('-');
    return parts.length >= 2 ? `${parts[0]}-${parts[1]}` : parts[0];
  }

  shouldShowGroupHeader(item: LineItemWithPicks, index: number): boolean {
    if (!this.groupByLocation) return false;
    if (index === 0) return true;

    const items = this.filteredItems;
    const prevItem = items[index - 1];
    return this.getLocationGroup(item.location) !== this.getLocationGroup(prevItem.location);
  }

  formatDate(date: string | null | undefined): string {
    if (!date) return '-';
    return new Date(date).toLocaleDateString();
  }

  print(): void {
    window.print();
  }
}
