// src/app/components/layout/global-search.component.ts
import { Component, OnInit, OnDestroy, ElementRef, HostListener } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule, Router } from '@angular/router';
import { Subject, Subscription, debounceTime, distinctUntilChanged, switchMap, of } from 'rxjs';
import { GlobalSearchService, SearchResult } from '../../services/global-search.service';

@Component({
  selector: 'app-global-search',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  template: `
    <div class="global-search position-relative">
      <!-- Desktop Search -->
      <div class="d-none d-md-block">
        <div class="input-group">
          <span class="input-group-text bg-transparent border-end-0">
            <i class="bi bi-search text-muted"></i>
          </span>
          <input
            type="text"
            class="form-control border-start-0 ps-0"
            placeholder="Search parts, orders..."
            [(ngModel)]="searchQuery"
            (input)="onSearchInput()"
            (focus)="showResults = true"
            (keydown)="onKeydown($event)"
          >
          <span class="input-group-text bg-transparent border-start-0 text-muted small" *ngIf="!searchQuery">
            <kbd class="bg-light border rounded px-1">Ctrl+K</kbd>
          </span>
        </div>

        <!-- Results Dropdown -->
        <div
          *ngIf="showResults && searchQuery.length >= 2"
          class="position-absolute top-100 start-0 end-0 bg-white border rounded-bottom shadow-sm mt-1 z-3"
          style="max-height: 400px; overflow-y: auto;"
        >
          <div *ngIf="loading" class="text-center py-3 text-muted">
            <div class="spinner-border spinner-border-sm me-2"></div>
            Searching...
          </div>

          <div *ngIf="!loading && results.length === 0" class="text-center py-3 text-muted">
            No results found
          </div>

          <div *ngIf="!loading && results.length > 0" class="list-group list-group-flush">
            <a
              *ngFor="let result of results; let i = index"
              [routerLink]="['/orders', result.order_id]"
              class="list-group-item list-group-item-action"
              [class.active]="i === selectedIndex"
              (click)="selectResult(result)"
              (mouseenter)="selectedIndex = i"
            >
              <div class="d-flex justify-content-between align-items-start">
                <div>
                  <span class="font-monospace fw-medium">{{ result.part_number }}</span>
                  <small class="text-muted ms-2" *ngIf="result.description">{{ result.description }}</small>
                </div>
                <span class="badge bg-light text-dark">SO-{{ result.so_number }}</span>
              </div>
              <div class="small text-muted mt-1">
                <span *ngIf="result.location" class="me-3">
                  <i class="bi bi-geo-alt me-1"></i>{{ result.location }}
                </span>
                <span>
                  <i class="bi bi-box me-1"></i>{{ result.total_picked }}/{{ result.total_qty_needed }} picked
                </span>
              </div>
            </a>
          </div>
        </div>
      </div>

      <!-- Mobile Search Button -->
      <div class="d-md-none">
        <button class="btn btn-outline-secondary" (click)="toggleMobileSearch()">
          <i class="bi bi-search"></i>
        </button>
      </div>

      <!-- Mobile Search Overlay -->
      <div
        *ngIf="showMobileSearch"
        class="mobile-search-overlay position-fixed top-0 start-0 end-0 bottom-0 bg-white z-3 d-md-none"
      >
        <div class="p-3">
          <div class="d-flex gap-2 mb-3">
            <input
              type="text"
              class="form-control"
              placeholder="Search parts, orders..."
              [(ngModel)]="searchQuery"
              (input)="onSearchInput()"
              autofocus
            >
            <button class="btn btn-outline-secondary" (click)="closeMobileSearch()">
              <i class="bi bi-x-lg"></i>
            </button>
          </div>

          <div *ngIf="loading" class="text-center py-3 text-muted">
            <div class="spinner-border spinner-border-sm me-2"></div>
            Searching...
          </div>

          <div *ngIf="!loading && searchQuery.length >= 2 && results.length === 0" class="text-center py-3 text-muted">
            No results found
          </div>

          <div *ngIf="!loading && results.length > 0" class="list-group">
            <a
              *ngFor="let result of results"
              [routerLink]="['/orders', result.order_id]"
              class="list-group-item list-group-item-action"
              (click)="selectResult(result)"
            >
              <div class="d-flex justify-content-between align-items-start">
                <div>
                  <span class="font-monospace fw-medium">{{ result.part_number }}</span>
                  <small class="text-muted d-block" *ngIf="result.description">{{ result.description }}</small>
                </div>
                <span class="badge bg-light text-dark">SO-{{ result.so_number }}</span>
              </div>
              <div class="small text-muted mt-1">
                <span *ngIf="result.location" class="me-3">
                  <i class="bi bi-geo-alt me-1"></i>{{ result.location }}
                </span>
                <span>
                  <i class="bi bi-box me-1"></i>{{ result.total_picked }}/{{ result.total_qty_needed }}
                </span>
              </div>
            </a>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .global-search {
      min-width: 280px;
    }

    .mobile-search-overlay {
      overflow-y: auto;
    }

    kbd {
      font-size: 0.75rem;
    }
  `]
})
export class GlobalSearchComponent implements OnInit, OnDestroy {
  searchQuery = '';
  results: SearchResult[] = [];
  loading = false;
  showResults = false;
  showMobileSearch = false;
  selectedIndex = 0;

  private searchSubject = new Subject<string>();
  private subscriptions: Subscription[] = [];

  constructor(
    private searchService: GlobalSearchService,
    private router: Router,
    private elementRef: ElementRef
  ) {}

  ngOnInit(): void {
    this.subscriptions.push(
      this.searchSubject.pipe(
        debounceTime(300),
        distinctUntilChanged()
      ).subscribe(query => {
        this.performSearch(query);
      }),
      this.searchService.results$.subscribe(results => {
        this.results = results;
      }),
      this.searchService.loading$.subscribe(loading => {
        this.loading = loading;
      })
    );
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  @HostListener('document:click', ['$event'])
  onDocumentClick(event: MouseEvent): void {
    if (!this.elementRef.nativeElement.contains(event.target)) {
      this.showResults = false;
    }
  }

  @HostListener('document:keydown', ['$event'])
  onGlobalKeydown(event: KeyboardEvent): void {
    // Ctrl+K or Cmd+K to focus search
    if ((event.ctrlKey || event.metaKey) && event.key === 'k') {
      event.preventDefault();
      const input = this.elementRef.nativeElement.querySelector('input');
      if (input) {
        input.focus();
        this.showResults = true;
      }
    }

    // Escape to close
    if (event.key === 'Escape') {
      this.showResults = false;
      this.showMobileSearch = false;
    }
  }

  onSearchInput(): void {
    this.selectedIndex = 0;
    if (this.searchQuery.length >= 2) {
      this.searchSubject.next(this.searchQuery);
    } else {
      this.results = [];
    }
  }

  onKeydown(event: KeyboardEvent): void {
    if (!this.showResults || this.results.length === 0) return;

    switch (event.key) {
      case 'ArrowDown':
        event.preventDefault();
        this.selectedIndex = Math.min(this.selectedIndex + 1, this.results.length - 1);
        break;
      case 'ArrowUp':
        event.preventDefault();
        this.selectedIndex = Math.max(this.selectedIndex - 1, 0);
        break;
      case 'Enter':
        event.preventDefault();
        if (this.results[this.selectedIndex]) {
          this.selectResult(this.results[this.selectedIndex]);
        }
        break;
    }
  }

  async performSearch(query: string): Promise<void> {
    if (query.length < 2) {
      this.searchService.clearResults();
      return;
    }

    await this.searchService.search(query);
  }

  selectResult(result: SearchResult): void {
    this.router.navigate(['/orders', result.order_id]);
    this.showResults = false;
    this.showMobileSearch = false;
    this.searchQuery = '';
    this.results = [];
  }

  toggleMobileSearch(): void {
    this.showMobileSearch = !this.showMobileSearch;
  }

  closeMobileSearch(): void {
    this.showMobileSearch = false;
    this.searchQuery = '';
    this.results = [];
  }
}

// src/components/layout/GlobalSearch.tsx
import { useState, useEffect, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { Search, X, MapPin, Package, Loader2 } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import { useGlobalSearch, type SearchResult } from '@/hooks/useGlobalSearch';

interface GlobalSearchProps {
  className?: string;
}

export function GlobalSearch({ className }: GlobalSearchProps) {
  const [query, setQuery] = useState('');
  const [isOpen, setIsOpen] = useState(false);
  const [isExpanded, setIsExpanded] = useState(false); // For mobile expand/collapse
  const [selectedIndex, setSelectedIndex] = useState(-1);
  const inputRef = useRef<HTMLInputElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const navigate = useNavigate();
  const { results, loading, search, clearResults } = useGlobalSearch();

  // Debounced search
  useEffect(() => {
    const timer = setTimeout(() => {
      if (query.trim().length >= 2) {
        search(query);
        setIsOpen(true);
      } else {
        clearResults();
        setIsOpen(false);
      }
    }, 300);

    return () => clearTimeout(timer);
  }, [query, search, clearResults]);

  // Handle click outside to close dropdown and collapse on mobile
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (
        containerRef.current &&
        !containerRef.current.contains(event.target as Node)
      ) {
        setIsOpen(false);
        // Collapse on mobile when clicking outside
        if (isExpanded && query.trim() === '') {
          setIsExpanded(false);
        }
      }
    }

    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, [isExpanded, query]);

  // Focus input when expanded on mobile
  useEffect(() => {
    if (isExpanded && inputRef.current) {
      inputRef.current.focus();
    }
  }, [isExpanded]);

  // Reset selected index when results change
  useEffect(() => {
    setSelectedIndex(-1);
  }, [results]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (!isOpen || results.length === 0) return;

    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        setSelectedIndex(prev => (prev < results.length - 1 ? prev + 1 : prev));
        break;
      case 'ArrowUp':
        e.preventDefault();
        setSelectedIndex(prev => (prev > 0 ? prev - 1 : -1));
        break;
      case 'Enter':
        e.preventDefault();
        if (selectedIndex >= 0 && selectedIndex < results.length) {
          handleResultClick(results[selectedIndex]);
        }
        break;
      case 'Escape':
        setIsOpen(false);
        inputRef.current?.blur();
        break;
    }
  };

  const handleGoToOrder = (result: SearchResult) => {
    navigate(`/orders/${result.order_id}`);
    setQuery('');
    setIsOpen(false);
    setIsExpanded(false); // Close mobile search
    clearResults();
  };

  const handleViewInParts = (result: SearchResult) => {
    navigate(`/parts?search=${encodeURIComponent(result.part_number)}`);
    setQuery('');
    setIsOpen(false);
    setIsExpanded(false); // Close mobile search
    clearResults();
  };

  // Keep legacy handler for keyboard navigation (defaults to order view)
  const handleResultClick = (result: SearchResult) => {
    handleGoToOrder(result);
  };

  const handleClear = () => {
    setQuery('');
    setIsOpen(false);
    clearResults();
    inputRef.current?.focus();
  };

  const handleFocus = () => {
    if (query.trim().length >= 2 && results.length > 0) {
      setIsOpen(true);
    }
  };

  return (
    <div ref={containerRef} className={cn('relative', className)}>
      {/* Mobile: Icon button that expands to full search */}
      {!isExpanded && (
        <Button
          variant="ghost"
          size="icon"
          className="lg:hidden h-9 w-9"
          onClick={() => setIsExpanded(true)}
          aria-label="Search"
        >
          <Search className="h-5 w-5" />
        </Button>
      )}

      {/* Mobile expanded search - full screen overlay style */}
      {isExpanded && (
        <div className="fixed inset-x-0 top-14 z-50 bg-background border-b shadow-lg p-4 lg:hidden">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
            <Input
              ref={inputRef}
              type="text"
              placeholder="Search parts..."
              value={query}
              onChange={(e) => setQuery(e.target.value)}
              onKeyDown={handleKeyDown}
              onFocus={handleFocus}
              className="pl-10 pr-10 h-11 w-full text-base"
            />
            <Button
              variant="ghost"
              size="icon"
              className="absolute right-1 top-1/2 -translate-y-1/2 h-9 w-9"
              onClick={() => {
                handleClear();
                setIsExpanded(false);
              }}
            >
              <X className="h-5 w-5" />
            </Button>
            {loading && (
              <Loader2 className="absolute right-12 top-1/2 -translate-y-1/2 h-4 w-4 animate-spin text-muted-foreground" />
            )}
          </div>
        </div>
      )}

      {/* Desktop: Always visible input */}
      <div className="relative hidden lg:block">
        <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          ref={!isExpanded ? inputRef : undefined}
          type="text"
          placeholder="Search parts across all orders..."
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          onKeyDown={handleKeyDown}
          onFocus={handleFocus}
          className="pl-10 pr-10 h-9 w-80"
        />
        {query && (
          <Button
            variant="ghost"
            size="icon"
            className="absolute right-1 top-1/2 -translate-y-1/2 h-7 w-7"
            onClick={handleClear}
          >
            <X className="h-4 w-4" />
          </Button>
        )}
        {loading && (
          <Loader2 className="absolute right-10 top-1/2 -translate-y-1/2 h-4 w-4 animate-spin text-muted-foreground" />
        )}
      </div>

      {/* Results Dropdown */}
      {isOpen && (
        <div
          ref={dropdownRef}
          className={cn(
            "bg-background border rounded-md shadow-lg z-50 max-h-96 overflow-y-auto",
            // Mobile: fixed position below the expanded search bar
            isExpanded && "fixed inset-x-0 top-[7.5rem] mx-4 lg:mx-0",
            // Desktop: absolute position below the input
            !isExpanded && "absolute top-full left-0 right-0 mt-1"
          )}
        >
          {results.length === 0 && !loading && query.trim().length >= 2 && (
            <div className="p-4 text-center text-muted-foreground">
              <Package className="mx-auto h-8 w-8 mb-2 opacity-50" />
              <p className="text-sm">No parts found matching "{query}"</p>
            </div>
          )}

          {results.length > 0 && (
            <div className="py-1">
              <div className="px-3 py-2 text-xs font-medium text-muted-foreground border-b">
                {results.length} result{results.length !== 1 ? 's' : ''} found
              </div>
              {results.map((result, index) => {
                const isComplete = result.total_picked >= result.total_qty_needed;
                const remaining = result.total_qty_needed - result.total_picked;

                return (
                  <div
                    key={`${result.id}-${result.order_id}`}
                    className={cn(
                      'w-full px-3 py-2 hover:bg-accent transition-colors',
                      selectedIndex === index && 'bg-accent',
                      isComplete && 'bg-green-50/50 dark:bg-green-950/20'
                    )}
                    onMouseEnter={() => setSelectedIndex(index)}
                  >
                    <div className="flex items-start justify-between gap-2">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2 flex-wrap">
                          <span className="font-mono font-semibold text-sm">
                            {result.part_number}
                          </span>
                          {result.location && (
                            <Badge variant="outline" className="gap-1 text-xs py-0">
                              <MapPin className="h-3 w-3" />
                              {result.location}
                            </Badge>
                          )}
                        </div>
                        {result.description && (
                          <p className="text-xs text-muted-foreground truncate mt-0.5">
                            {result.description}
                          </p>
                        )}
                        <p className="text-xs text-muted-foreground mt-1">
                          Order: <span className="font-medium">SO-{result.so_number}</span>
                        </p>
                      </div>
                      <div className="text-right shrink-0">
                        <div className="text-sm font-medium">
                          <span className={cn(isComplete && 'text-green-600 dark:text-green-400')}>
                            {result.total_picked}
                          </span>
                          <span className="text-muted-foreground"> / {result.total_qty_needed}</span>
                        </div>
                        {isComplete ? (
                          <Badge variant="success" className="text-xs mt-0.5">Complete</Badge>
                        ) : (
                          <span className="text-xs text-muted-foreground">
                            {remaining} left
                          </span>
                        )}
                      </div>
                    </div>
                    {/* Navigation buttons */}
                    <div className="flex items-center gap-2 mt-2">
                      <Button
                        size="sm"
                        variant="default"
                        className="h-7 text-xs flex-1 sm:flex-none"
                        onClick={() => handleGoToOrder(result)}
                      >
                        Order
                      </Button>
                      <Button
                        size="sm"
                        variant="outline"
                        className="h-7 text-xs flex-1 sm:flex-none"
                        onClick={() => handleViewInParts(result)}
                      >
                        Parts
                      </Button>
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          {query.trim().length >= 2 && results.length > 0 && (
            <div className="px-3 py-2 text-xs text-muted-foreground border-t bg-muted/30">
              Press <kbd className="px-1 py-0.5 bg-muted rounded text-[10px]">Enter</kbd> to select,{' '}
              <kbd className="px-1 py-0.5 bg-muted rounded text-[10px]">Esc</kbd> to close
            </div>
          )}
        </div>
      )}
    </div>
  );
}
