// AngularBootstrap/src/app/pages/parts-catalog/parts-catalog.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { Subscription } from 'rxjs';
import { NgbModal, NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { PartsService, Part, PartWithStats, ClassificationType } from '../../services/parts.service';
import { PartDetailComponent } from '../../components/parts/part-detail.component';
import { SupabaseService } from '../../services/supabase.service';

type PartSortOption = 'part-number' | 'description' | 'classification' | 'location';

@Component({
  selector: 'app-parts-catalog',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  template: `
    <div class="container-fluid py-3">
      <!-- Header -->
      <div class="d-flex flex-column flex-md-row justify-content-between align-items-start align-items-md-center mb-3 gap-2">
        <div>
          <h1 class="h3 mb-1">Parts Catalog</h1>
          <p class="text-muted small mb-0">Manage your parts catalog with classifications and relationships</p>
        </div>
        <div class="d-flex gap-2">
          <button class="btn btn-outline-secondary">
            <i class="bi bi-download me-1"></i> Export
          </button>
          <button
            class="btn btn-outline-primary"
            (click)="handleAutoDetectAssemblies()"
            [disabled]="autoDetecting">
            <i class="bi bi-lightning-charge me-1"></i>
            {{ autoDetecting ? 'Detecting...' : 'Auto-Detect Assemblies' }}
          </button>
          <button class="btn btn-primary" (click)="showNewPartDialog()">
            <i class="bi bi-plus-lg me-1"></i> New Part
          </button>
        </div>
      </div>

      <!-- Filters -->
      <div class="card mb-3">
        <div class="card-body">
          <div class="row g-3">
            <!-- Search -->
            <div class="col-md-4">
              <input
                type="search"
                class="form-control"
                placeholder="Search by part number, description, or location..."
                [(ngModel)]="searchQuery"
                (ngModelChange)="applyFilters()"
              />
            </div>

            <!-- Classification Filter -->
            <div class="col-md-4">
              <select class="form-select" [(ngModel)]="classificationFilter" (ngModelChange)="applyFilters()">
                <option value="all">All Classifications</option>
                <option value="purchased">Purchased</option>
                <option value="manufactured">Manufactured</option>
                <option value="assembly">Assembly</option>
                <option value="modified">Modified</option>
              </select>
            </div>

            <!-- Sort -->
            <div class="col-md-4">
              <select class="form-select" [(ngModel)]="sortBy" (ngModelChange)="applyFilters()">
                <option value="part-number">Sort by Part Number</option>
                <option value="description">Sort by Description</option>
                <option value="classification">Sort by Classification</option>
                <option value="location">Sort by Location</option>
              </select>
            </div>
          </div>

          <div class="mt-2">
            <small class="text-muted">
              {{ filteredParts.length }} part(s)
            </small>
          </div>
        </div>
      </div>

      <!-- Parts List -->
      <div *ngIf="loading" class="text-center py-5">
        <div class="spinner-border text-primary" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
        <p class="text-muted mt-3">Loading parts...</p>
      </div>

      <div *ngIf="!loading && filteredParts.length === 0" class="card">
        <div class="card-body text-center py-5">
          <p class="text-muted">
            {{ searchQuery || classificationFilter !== 'all' ? 'No parts match your filters' : 'No parts yet. Create one to get started.' }}
          </p>
          <button *ngIf="!searchQuery && classificationFilter === 'all'" class="btn btn-primary mt-2" (click)="showNewPartDialog()">
            Create Part
          </button>
        </div>
      </div>

      <div *ngIf="!loading && filteredParts.length > 0" class="row g-3">
        <div *ngFor="let part of filteredParts" class="col-12">
          <div class="card hover-shadow" style="cursor: pointer;" (click)="openPartDetail(part.id)">
            <div class="card-body py-3">
              <div class="row g-3 align-items-center">
                <!-- Part Number & Classification -->
                <div class="col-12 col-sm-3 col-lg-2">
                  <div class="d-flex align-items-center gap-2">
                    <div class="font-monospace fw-semibold">{{ part.part_number }}</div>
                    <button class="btn btn-sm btn-link p-0 text-secondary" (click)="copyPartNumber(part.part_number, $event)" title="Copy part number">
                      <i class="bi" [ngClass]="copiedPartNumber === part.part_number ? 'bi-check-lg text-success' : 'bi-clipboard'"></i>
                    </button>
                  </div>
                  <span *ngIf="part.classification_type" [class]="getClassificationBadgeClass(part.classification_type) + ' mt-1'">
                    {{ getClassificationLabel(part.classification_type) }}
                  </span>
                </div>

                <!-- Description -->
                <div class="col-12 col-sm-4 col-lg-3">
                  <div class="small text-muted text-truncate-2">
                    <span *ngIf="part.description">{{ part.description }}</span>
                    <span *ngIf="!part.description" class="fst-italic">No description</span>
                  </div>
                </div>

                <!-- Location -->
                <div class="col-6 col-sm-2 col-lg-2">
                  <div class="small text-muted" style="font-size: 0.75rem;">Location</div>
                  <div class="small fw-medium">
                    <span *ngIf="part.default_location">{{ part.default_location }}</span>
                    <span *ngIf="!part.default_location" class="text-muted fst-italic">—</span>
                  </div>
                </div>

                <!-- BOM Stats -->
                <div class="col-6 col-sm-2 col-lg-2">
                  <div class="small text-muted" style="font-size: 0.75rem;">BOM</div>
                  <div class="small">
                    <span *ngIf="part.child_count > 0" class="fw-medium">{{ part.child_count }} parts</span>
                    <span *ngIf="part.used_in_count > 0 && part.child_count > 0" class="text-muted"> • </span>
                    <span *ngIf="part.used_in_count > 0" class="text-muted">{{ part.used_in_count }} assy</span>
                    <span *ngIf="part.child_count === 0 && part.used_in_count === 0" class="text-muted fst-italic">—</span>
                  </div>
                </div>

                <!-- Dates -->
                <div class="col-6 col-sm-2 col-lg-2">
                  <div class="small text-muted" style="font-size: 0.75rem;">Updated</div>
                  <div class="small">{{ part.updated_at | date:'shortDate' }}</div>
                </div>

                <!-- Edit Button -->
                <div class="col-6 col-sm-1 col-lg-1 text-end">
                  <button class="btn btn-sm btn-ghost-secondary" (click)="openPartDetail(part.id); $event.stopPropagation()">
                    <i class="bi bi-pencil"></i>
                  </button>
                </div>
              </div>

              <!-- Notes Row (if present) -->
              <div *ngIf="part.notes" class="row mt-3 pt-3 border-top">
                <div class="col-12">
                  <div class="small text-muted">
                    <span class="fw-medium">Notes:</span> {{ part.notes }}
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .hover-shadow {
      transition: box-shadow 0.2s ease-in-out;
    }
    .hover-shadow:hover {
      box-shadow: 0 0.125rem 0.5rem rgba(0, 0, 0, 0.15);
    }
    .min-w-0 {
      min-width: 0;
    }
    .btn-ghost-secondary {
      color: #6c757d;
      background-color: transparent;
      border: none;
    }
    .btn-ghost-secondary:hover {
      color: #495057;
      background-color: rgba(0, 0, 0, 0.05);
    }
    .text-truncate-2 {
      display: -webkit-box;
      -webkit-line-clamp: 2;
      -webkit-box-orient: vertical;
      overflow: hidden;
    }
  `]
})
export class PartsCatalogComponent implements OnInit, OnDestroy {
  parts: PartWithStats[] = [];
  filteredParts: PartWithStats[] = [];
  loading = true;
  searchQuery = '';
  classificationFilter: ClassificationType | 'all' = 'all';
  sortBy: PartSortOption = 'part-number';
  autoDetecting = false;
  autoDetectResults: Array<{
    assembly_name: string;
    components_count: number;
    created_relationships: number;
  }> | null = null;
  copiedPartNumber: string | null = null;

  private subscription?: Subscription;

  constructor(
    private partsService: PartsService,
    private modalService: NgbModal,
    private supabaseService: SupabaseService
  ) {}

  ngOnInit(): void {
    this.subscription = this.partsService.parts$.subscribe((parts) => {
      this.parts = parts;
      this.applyFilters();
    });

    this.partsService.loading$.subscribe((loading) => {
      this.loading = loading;
    });
  }

  ngOnDestroy(): void {
    this.subscription?.unsubscribe();
  }

  applyFilters(): void {
    let filtered = [...this.parts];

    // Search filter
    if (this.searchQuery) {
      const query = this.searchQuery.toLowerCase();
      filtered = filtered.filter((part) =>
        part.part_number.toLowerCase().includes(query) ||
        part.description?.toLowerCase().includes(query) ||
        part.default_location?.toLowerCase().includes(query)
      );
    }

    // Classification filter
    if (this.classificationFilter !== 'all') {
      filtered = filtered.filter((part) => part.classification_type === this.classificationFilter);
    }

    // Sort
    filtered.sort((a, b) => {
      switch (this.sortBy) {
        case 'part-number':
          return a.part_number.localeCompare(b.part_number, undefined, { numeric: true });
        case 'description':
          return (a.description || '').localeCompare(b.description || '');
        case 'classification':
          return (a.classification_type || '').localeCompare(b.classification_type || '');
        case 'location':
          return (a.default_location || '').localeCompare(b.default_location || '');
        default:
          return 0;
      }
    });

    this.filteredParts = filtered;
  }

  getClassificationLabel(type: ClassificationType): string {
    const labels: Record<ClassificationType, string> = {
      purchased: 'Purchased',
      manufactured: 'Manufactured',
      assembly: 'Assembly',
      modified: 'Modified'
    };
    return labels[type];
  }

  getClassificationBadgeClass(type: ClassificationType): string {
    const classes: Record<ClassificationType, string> = {
      purchased: 'badge bg-primary',
      manufactured: 'badge bg-warning text-dark',
      assembly: 'badge bg-secondary',
      modified: 'badge bg-info text-dark'
    };
    return classes[type];
  }

  showNewPartDialog(): void {
    const modalRef = this.modalService.open(PartDetailComponent, {
      size: 'xl',
      backdrop: 'static'
    });
    modalRef.componentInstance.isNew = true;
  }

  openPartDetail(partId: string): void {
    const modalRef = this.modalService.open(PartDetailComponent, {
      size: 'xl',
      backdrop: 'static',
      scrollable: true
    });
    modalRef.componentInstance.partId = partId;
  }

  async handleAutoDetectAssemblies(): Promise<void> {
    try {
      this.autoDetecting = true;
      const { data, error } = await this.supabaseService.rpc('auto_detect_assemblies_from_orders', {});

      if (error) throw error;

      this.autoDetectResults = data || [];
      this.partsService.refetch(); // Refresh parts list

      // Show results modal
      const modalRef = this.modalService.open(AutoDetectResultsModal, { size: 'lg' });
      modalRef.componentInstance.results = this.autoDetectResults;
    } catch (error) {
      console.error('Error auto-detecting assemblies:', error);
      alert('Failed to auto-detect assemblies. Please try again.');
    } finally {
      this.autoDetecting = false;
    }
  }

  async copyPartNumber(partNumber: string, event: Event): Promise<void> {
    event.stopPropagation();
    try {
      await navigator.clipboard.writeText(partNumber);
      this.copiedPartNumber = partNumber;
      setTimeout(() => {
        if (this.copiedPartNumber === partNumber) {
          this.copiedPartNumber = null;
        }
      }, 2000);
    } catch (err) {
      console.error('Failed to copy:', err);
    }
  }
}

// Auto-Detect Results Modal Component
@Component({
  selector: 'app-auto-detect-results-modal',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="modal-header">
      <h5 class="modal-title">Auto-Detect Assemblies Results</h5>
      <button type="button" class="btn-close" (click)="activeModal.dismiss()"></button>
    </div>
    <div class="modal-body">
      <div *ngIf="results && results.length > 0; else noResults">
        <p class="text-muted">Found {{ results.length }} assemblies from existing orders:</p>
        <div class="list-group">
          <div *ngFor="let result of results" class="list-group-item">
            <div class="d-flex justify-content-between align-items-center">
              <div>
                <h6 class="mb-1">{{ result.assembly_name }}</h6>
                <small class="text-muted">
                  {{ result.components_count }} components, {{ result.created_relationships }} new relationships created
                </small>
              </div>
              <span class="badge bg-secondary">{{ result.components_count }}</span>
            </div>
          </div>
        </div>
      </div>
      <ng-template #noResults>
        <p class="text-center text-muted py-5">No assemblies found in existing orders.</p>
      </ng-template>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" (click)="activeModal.close()">Close</button>
    </div>
  `
})
class AutoDetectResultsModal {
  results: Array<{
    assembly_name: string;
    components_count: number;
    created_relationships: number;
  }> | null = null;

  constructor(public activeModal: NgbActiveModal) {}
}

// src/pages/PartsCatalog.tsx
import { useState, useMemo } from 'react';
import { Plus, Package, Download, Edit2, Zap } from 'lucide-react';
import { supabase } from '@/lib/supabase';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Label } from '@/components/ui/label';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useParts } from '@/hooks/useParts';
import { cn } from '@/lib/utils';
import type { ClassificationType, Part } from '@/types';
import { PartDetail } from '@/components/parts/PartDetail';
import {
  UnifiedFilterBar,
  type StatusButtonOption,
  type SortOption,
} from '@/components/filters';

type PartSortOption = 'part-number' | 'description' | 'classification' | 'location';

const CLASSIFICATION_OPTIONS: StatusButtonOption<ClassificationType | 'all'>[] = [
  { value: 'all', label: 'All', shortLabel: 'All', icon: Package, title: 'Show all parts' },
  { value: 'purchased', label: 'Purchased', shortLabel: 'Purch.', icon: Package, title: 'Show purchased parts' },
  { value: 'manufactured', label: 'Manufactured', shortLabel: 'Mfg.', icon: Package, title: 'Show manufactured parts' },
  { value: 'assembly', label: 'Assembly', shortLabel: 'Assy.', icon: Package, title: 'Show assemblies' },
  { value: 'modified', label: 'Modified', shortLabel: 'Mod.', icon: Package, title: 'Show modified parts' },
];

const SORT_OPTIONS: SortOption<PartSortOption>[] = [
  { value: 'part-number', label: 'Part Number' },
  { value: 'description', label: 'Description' },
  { value: 'classification', label: 'Classification' },
  { value: 'location', label: 'Location' },
];

function getClassificationColor(classification: ClassificationType | null): string {
  if (!classification) return 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200';

  switch (classification) {
    case 'purchased':
      return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200';
    case 'manufactured':
      return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200';
    case 'assembly':
      return 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200';
    case 'modified':
      return 'bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200';
    default:
      return 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200';
  }
}

export function PartsCatalog() {
  const { parts, loading, createPart, updatePart, refetch } = useParts();
  const [searchQuery, setSearchQuery] = useState('');
  const [classificationFilter, setClassificationFilter] = useState<ClassificationType | 'all'>('all');
  const [sortBy, setSortBy] = useState<PartSortOption>('part-number');
  const [showNewPartDialog, setShowNewPartDialog] = useState(false);
  const [selectedPartId, setSelectedPartId] = useState<string | null>(null);
  const [autoDetecting, setAutoDetecting] = useState(false);
  const [autoDetectResults, setAutoDetectResults] = useState<{
    assembly_name: string;
    components_count: number;
    created_relationships: number;
  }[] | null>(null);
  const [newPart, setNewPart] = useState({
    part_number: '',
    description: '',
    classification_type: '' as ClassificationType | '',
    default_location: '',
    notes: '',
  });

  const handleAutoDetectAssemblies = async () => {
    try {
      setAutoDetecting(true);
      const { data, error } = await supabase.rpc('auto_detect_assemblies_from_orders');

      if (error) throw error;

      setAutoDetectResults(data || []);
      await refetch(); // Refresh parts list
    } catch (error) {
      console.error('Error auto-detecting assemblies:', error);
      alert('Failed to auto-detect assemblies. Please try again.');
    } finally {
      setAutoDetecting(false);
    }
  };

  const filteredAndSortedParts = useMemo(() => {
    // Filter
    const filtered = parts.filter((part) => {
      const matchesSearch =
        part.part_number.toLowerCase().includes(searchQuery.toLowerCase()) ||
        part.description?.toLowerCase().includes(searchQuery.toLowerCase()) ||
        part.default_location?.toLowerCase().includes(searchQuery.toLowerCase());

      const matchesClassification =
        classificationFilter === 'all' || part.classification_type === classificationFilter;

      return matchesSearch && matchesClassification;
    });

    // Sort
    return [...filtered].sort((a, b) => {
      switch (sortBy) {
        case 'part-number':
          return a.part_number.localeCompare(b.part_number, undefined, { numeric: true });
        case 'description':
          return (a.description || '').localeCompare(b.description || '');
        case 'classification':
          return (a.classification_type || '').localeCompare(b.classification_type || '');
        case 'location':
          return (a.default_location || '').localeCompare(b.default_location || '');
        default:
          return 0;
      }
    });
  }, [parts, searchQuery, classificationFilter, sortBy]);

  const handleCreatePart = async () => {
    if (!newPart.part_number.trim()) return;

    await createPart({
      part_number: newPart.part_number.trim(),
      description: newPart.description.trim() || null,
      classification_type: newPart.classification_type || null,
      default_location: newPart.default_location.trim() || null,
      base_part_id: null,
      notes: newPart.notes.trim() || null,
    });

    setNewPart({
      part_number: '',
      description: '',
      classification_type: '',
      default_location: '',
      notes: '',
    });
    setShowNewPartDialog(false);
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="text-3xl font-bold">Parts Catalog</h1>
          <p className="text-muted-foreground">
            Manage your parts catalog with classifications and relationships
          </p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline">
            <Download className="mr-2 h-4 w-4" />
            Export
          </Button>
          <Button
            variant="outline"
            onClick={handleAutoDetectAssemblies}
            disabled={autoDetecting}
          >
            <Zap className="mr-2 h-4 w-4" />
            {autoDetecting ? 'Detecting...' : 'Auto-Detect Assemblies'}
          </Button>
          <Button onClick={() => setShowNewPartDialog(true)}>
            <Plus className="mr-2 h-4 w-4" />
            New Part
          </Button>
        </div>
      </div>

      {/* Filters */}
      <UnifiedFilterBar
        searchValue={searchQuery}
        onSearchChange={setSearchQuery}
        searchPlaceholder="Search by part number, description, or location..."
        statusButtons={CLASSIFICATION_OPTIONS}
        statusValue={classificationFilter}
        onStatusChange={setClassificationFilter}
        sort={{
          options: SORT_OPTIONS,
          value: sortBy,
          onChange: setSortBy,
        }}
        resultCount={filteredAndSortedParts.length}
      />

      {/* Parts List */}
      {loading ? (
        <Card>
          <CardContent className="py-8 text-center">
            <p className="text-muted-foreground">Loading parts...</p>
          </CardContent>
        </Card>
      ) : filteredAndSortedParts.length === 0 ? (
        <Card>
          <CardContent className="py-8 text-center">
            <p className="text-muted-foreground">
              {searchQuery || classificationFilter !== 'all'
                ? 'No parts match your filters'
                : 'No parts yet. Create one to get started.'}
            </p>
            {!searchQuery && classificationFilter === 'all' && (
              <div className="mt-4">
                <Button onClick={() => setShowNewPartDialog(true)}>
                  Create Part
                </Button>
              </div>
            )}
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {filteredAndSortedParts.map((part) => (
            <Card
              key={part.id}
              className="hover:shadow-md transition-shadow cursor-pointer"
              onClick={() => setSelectedPartId(part.id)}
            >
              <CardContent className="py-4">
                <div className="grid grid-cols-12 gap-4 items-center">
                  {/* Part Number & Classification */}
                  <div className="col-span-12 sm:col-span-3 lg:col-span-2">
                    <div className="font-mono font-semibold text-base">{part.part_number}</div>
                    {part.classification_type && (
                      <Badge className={cn("mt-1", getClassificationColor(part.classification_type))}>
                        {part.classification_type}
                      </Badge>
                    )}
                  </div>

                  {/* Description */}
                  <div className="col-span-12 sm:col-span-4 lg:col-span-3">
                    <div className="text-sm text-muted-foreground line-clamp-2">
                      {part.description || <span className="italic">No description</span>}
                    </div>
                  </div>

                  {/* Location */}
                  <div className="col-span-6 sm:col-span-2 lg:col-span-2">
                    <div className="text-xs text-muted-foreground">Location</div>
                    <div className="text-sm font-medium">
                      {part.default_location || <span className="text-muted-foreground italic">—</span>}
                    </div>
                  </div>

                  {/* BOM Stats */}
                  <div className="col-span-6 sm:col-span-2 lg:col-span-2">
                    <div className="text-xs text-muted-foreground">BOM</div>
                    <div className="text-sm">
                      {part.child_count > 0 && <span className="font-medium">{part.child_count} parts</span>}
                      {part.used_in_count > 0 && part.child_count > 0 && <span className="text-muted-foreground"> • </span>}
                      {part.used_in_count > 0 && <span className="text-muted-foreground">{part.used_in_count} assy</span>}
                      {part.child_count === 0 && part.used_in_count === 0 && <span className="text-muted-foreground italic">—</span>}
                    </div>
                  </div>

                  {/* Dates */}
                  <div className="col-span-6 sm:col-span-2 lg:col-span-2">
                    <div className="text-xs text-muted-foreground">Updated</div>
                    <div className="text-sm">
                      {new Date(part.updated_at).toLocaleDateString()}
                    </div>
                  </div>

                  {/* Edit Button */}
                  <div className="col-span-6 sm:col-span-1 lg:col-span-1 flex justify-end">
                    <Button
                      variant="ghost"
                      size="icon"
                      onClick={(e) => {
                        e.stopPropagation();
                        setSelectedPartId(part.id);
                      }}
                    >
                      <Edit2 className="h-4 w-4" />
                    </Button>
                  </div>
                </div>

                {/* Notes Row (if present) */}
                {part.notes && (
                  <div className="mt-3 pt-3 border-t text-xs text-muted-foreground">
                    <span className="font-medium">Notes:</span> {part.notes}
                  </div>
                )}
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      {/* New Part Dialog */}
      <Dialog open={showNewPartDialog} onOpenChange={setShowNewPartDialog}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Create New Part</DialogTitle>
          </DialogHeader>
          <div className="grid grid-cols-2 gap-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="part_number">Part Number *</Label>
              <Input
                id="part_number"
                placeholder="e.g., 12345-001"
                value={newPart.part_number}
                onChange={(e) =>
                  setNewPart({ ...newPart, part_number: e.target.value })
                }
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="classification_type">Classification</Label>
              <Select
                value={newPart.classification_type}
                onValueChange={(value) =>
                  setNewPart({ ...newPart, classification_type: value as ClassificationType })
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select classification" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="purchased">Purchased</SelectItem>
                  <SelectItem value="manufactured">Manufactured</SelectItem>
                  <SelectItem value="assembly">Assembly</SelectItem>
                  <SelectItem value="modified">Modified</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2 col-span-2">
              <Label htmlFor="description">Description</Label>
              <Input
                id="description"
                placeholder="Part description"
                value={newPart.description}
                onChange={(e) =>
                  setNewPart({ ...newPart, description: e.target.value })
                }
              />
            </div>
            <div className="space-y-2 col-span-2">
              <Label htmlFor="default_location">Default Location</Label>
              <Input
                id="default_location"
                placeholder="e.g., A-01-03"
                value={newPart.default_location}
                onChange={(e) =>
                  setNewPart({ ...newPart, default_location: e.target.value })
                }
              />
            </div>
            <div className="space-y-2 col-span-2">
              <Label htmlFor="notes">Notes</Label>
              <Textarea
                id="notes"
                placeholder="Any additional notes..."
                value={newPart.notes}
                onChange={(e) =>
                  setNewPart({ ...newPart, notes: e.target.value })
                }
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowNewPartDialog(false)}>
              Cancel
            </Button>
            <Button
              onClick={handleCreatePart}
              disabled={!newPart.part_number.trim()}
            >
              Create Part
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Auto-Detect Results Dialog */}
      <Dialog open={!!autoDetectResults} onOpenChange={() => setAutoDetectResults(null)}>
        <DialogContent className="max-w-2xl">
          <DialogHeader>
            <DialogTitle>Auto-Detect Assemblies Results</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            {autoDetectResults && autoDetectResults.length > 0 ? (
              <>
                <p className="text-sm text-muted-foreground">
                  Found {autoDetectResults.length} assemblies from existing orders:
                </p>
                <div className="max-h-96 overflow-y-auto space-y-2">
                  {autoDetectResults.map((result, index) => (
                    <Card key={index}>
                      <CardContent className="p-4">
                        <div className="flex items-center justify-between">
                          <div>
                            <h4 className="font-medium">{result.assembly_name}</h4>
                            <p className="text-sm text-muted-foreground">
                              {result.components_count} components, {result.created_relationships} new relationships created
                            </p>
                          </div>
                          <Badge variant="secondary">{result.components_count}</Badge>
                        </div>
                      </CardContent>
                    </Card>
                  ))}
                </div>
              </>
            ) : (
              <p className="text-center text-muted-foreground py-8">
                No assemblies found in existing orders.
              </p>
            )}
          </div>
          <DialogFooter>
            <Button onClick={() => setAutoDetectResults(null)}>Close</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Part Detail Dialog */}
      {selectedPartId && (
        <PartDetail
          partId={selectedPartId}
          open={!!selectedPartId}
          onClose={() => setSelectedPartId(null)}
        />
      )}
    </div>
  );
}
