// src/pages/Import.tsx
import { useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Upload, FileSpreadsheet, AlertCircle, CheckCircle2, X, Download, Database, FileText } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { parseEnhancedExcelFile, parseCsvFile } from '@/lib/excelParser';
import { downloadImportTemplate } from '@/lib/excelTemplate';
import { useOrders } from '@/hooks/useOrders';
import { usePartsCatalog } from '@/hooks/usePartsCatalog';
import { useBOMTemplates } from '@/hooks/useBOMTemplates';
import { DuplicatePartsDialog } from '@/components/dialogs/DuplicatePartsDialog';
import { TemplateSelectDialog } from '@/components/dialogs/TemplateSelectDialog';
import type { ImportedOrder, PartConflict, BOMTemplateWithItems } from '@/types';

export function Import() {
  const navigate = useNavigate();
  const { importOrder } = useOrders();
  const {
    parts: catalogParts,
    checkForConflicts,
    applyConflictResolutions,
    savePartsFromImport
  } = usePartsCatalog();
  const [isDragging, setIsDragging] = useState(false);
  const [parseResult, setParseResult] = useState<{
    order: ImportedOrder;
    errors: string[];
    warnings: string[];
  } | null>(null);
  const [parseErrors, setParseErrors] = useState<string[]>([]);
  const [isImporting, setIsImporting] = useState(false);
  const [conflicts, setConflicts] = useState<PartConflict[]>([]);
  const [showConflictDialog, setShowConflictDialog] = useState(false);
  const [saveToCatalog, setSaveToCatalog] = useState(true);
  const [showTemplateDialog, setShowTemplateDialog] = useState(false);
  const { templates } = useBOMTemplates();

  const handleFile = async (file: File) => {
    setParseResult(null);
    setParseErrors([]);
    setConflicts([]);

    const isExcel =
      file.name.endsWith('.xlsx') ||
      file.name.endsWith('.xls') ||
      file.type.includes('spreadsheet');
    const isCsv = file.name.endsWith('.csv') || file.type === 'text/csv';

    if (!isExcel && !isCsv) {
      setParseErrors(['Please upload an Excel (.xlsx) or CSV file']);
      return;
    }

    const result = isExcel
      ? await parseEnhancedExcelFile(file)
      : await parseCsvFile(file);

    if (result.success && result.order) {
      setParseResult({
        order: result.order,
        errors: result.errors,
        warnings: result.warnings,
      });

      // Check for conflicts with parts catalog
      if (catalogParts.length > 0) {
        const foundConflicts = checkForConflicts(result.order.line_items);
        if (foundConflicts.length > 0) {
          setConflicts(foundConflicts);
          setShowConflictDialog(true);
        }
      }
    } else {
      setParseErrors(result.errors);
    }
  };

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);

    const file = e.dataTransfer.files[0];
    if (file) {
      handleFile(file);
    }
  }, []);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(true);
  }, []);

  const handleDragLeave = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setIsDragging(false);
  }, []);

  const handleFileInput = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      handleFile(file);
    }
  };

  const handleImport = async () => {
    if (!parseResult?.order) return;

    setIsImporting(true);

    // Apply any conflict resolutions first
    if (conflicts.length > 0) {
      await applyConflictResolutions(conflicts);
    }

    // Save parts to catalog if enabled
    if (saveToCatalog) {
      await savePartsFromImport(parseResult.order.line_items, true);
    }

    const result = await importOrder(parseResult.order);
    setIsImporting(false);

    if (result) {
      navigate(`/orders/${result.id}`);
    }
  };

  const handleConflictResolve = (resolvedConflicts: PartConflict[]) => {
    setConflicts(resolvedConflicts);
    setShowConflictDialog(false);
  };

  const handleTemplateSelect = (template: BOMTemplateWithItems) => {
    // Create an imported order from the template
    const order: ImportedOrder = {
      so_number: '', // Will be filled in by user
      tools: [{ tool_number: '1', tool_model: template.tool_model || undefined }],
      line_items: template.items.map(item => ({
        part_number: item.part_number,
        description: item.description || undefined,
        location: item.location || undefined,
        qty_per_unit: item.qty_per_unit,
        total_qty_needed: item.qty_per_unit,
      })),
    };

    setParseResult({
      order,
      errors: [],
      warnings: ['Template loaded. You may need to adjust SO number and tool quantities.'],
    });

    // Check for conflicts
    if (catalogParts.length > 0) {
      const foundConflicts = checkForConflicts(order.line_items);
      if (foundConflicts.length > 0) {
        setConflicts(foundConflicts);
      }
    }
  };

  const clearResult = () => {
    setParseResult(null);
    setParseErrors([]);
    setConflicts([]);
  };

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold">Import Order</h1>
        <p className="text-muted-foreground">
          Upload an Excel or CSV file to import a sales order
        </p>
      </div>

      {/* Drop Zone */}
      {!parseResult && (
        <Card>
          <CardContent className="pt-6">
            <div
              className={`
                border-2 border-dashed rounded-lg p-12 text-center transition-colors
                ${isDragging ? 'border-primary bg-primary/5' : 'border-muted-foreground/25'}
              `}
              onDrop={handleDrop}
              onDragOver={handleDragOver}
              onDragLeave={handleDragLeave}
            >
              <Upload className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
              <p className="text-lg font-medium mb-2">
                Drag and drop your file here
              </p>
              <p className="text-muted-foreground mb-4">
                Supports Excel (.xlsx) and CSV files
              </p>
              <div className="flex items-center gap-2 justify-center">
                <label htmlFor="file-upload">
                  <Button asChild>
                    <span>
                      <FileSpreadsheet className="mr-2 h-4 w-4" />
                      Browse Files
                    </span>
                  </Button>
                </label>
                <input
                  id="file-upload"
                  type="file"
                  accept=".xlsx,.xls,.csv"
                  onChange={handleFileInput}
                  className="hidden"
                />
                {templates.length > 0 && (
                  <Button variant="outline" onClick={() => setShowTemplateDialog(true)}>
                    <FileText className="mr-2 h-4 w-4" />
                    Use Template
                  </Button>
                )}
              </div>
            </div>

            {/* Parse Errors */}
            {parseErrors.length > 0 && (
              <div className="mt-4 p-4 bg-destructive/10 rounded-lg">
                <div className="flex items-center gap-2 text-destructive mb-2">
                  <AlertCircle className="h-5 w-5" />
                  <span className="font-medium">Import Failed</span>
                </div>
                <ul className="list-disc list-inside text-sm">
                  {parseErrors.map((error, i) => (
                    <li key={i}>{error}</li>
                  ))}
                </ul>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Preview */}
      {parseResult && (
        <Card>
          <CardHeader className="flex flex-row items-center justify-between">
            <CardTitle className="flex items-center gap-2">
              <CheckCircle2 className="h-5 w-5 text-green-600 dark:text-green-400" />
              Preview: SO-{parseResult.order.so_number}
            </CardTitle>
            <Button variant="ghost" size="icon" onClick={clearResult}>
              <X className="h-4 w-4" />
            </Button>
          </CardHeader>
          <CardContent className="space-y-6">
            {/* Warnings */}
            {parseResult.warnings.length > 0 && (
              <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg dark:bg-yellow-950/20 dark:border-yellow-800">
                <p className="font-medium text-yellow-800 dark:text-yellow-200 mb-2">Warnings</p>
                <ul className="list-disc list-inside text-sm text-yellow-700 dark:text-yellow-300">
                  {parseResult.warnings.map((warning, i) => (
                    <li key={i}>{warning}</li>
                  ))}
                </ul>
              </div>
            )}

            {/* Order Info */}
            <div>
              <h3 className="font-medium mb-2">Order Details</h3>
              <div className="grid grid-cols-2 gap-4 text-sm">
                <div>
                  <span className="text-muted-foreground">SO Number:</span>
                  <span className="ml-2 font-medium">
                    {parseResult.order.so_number}
                  </span>
                </div>
                {parseResult.order.po_number && (
                  <div>
                    <span className="text-muted-foreground">PO Number:</span>
                    <span className="ml-2 font-medium">
                      {parseResult.order.po_number}
                    </span>
                  </div>
                )}
                {parseResult.order.customer_name && (
                  <div>
                    <span className="text-muted-foreground">Customer:</span>
                    <span className="ml-2 font-medium">
                      {parseResult.order.customer_name}
                    </span>
                  </div>
                )}
              </div>
            </div>

            {/* Tools */}
            <div>
              <h3 className="font-medium mb-2">
                Tools ({parseResult.order.tools.length})
              </h3>
              <div className="flex flex-wrap gap-2">
                {parseResult.order.tools.map((tool, i) => (
                  <Badge key={i} variant="secondary">
                    {tool.tool_number}
                    {tool.tool_model && ` [${tool.tool_model}]`}
                    {tool.serial_number && ` (SN: ${tool.serial_number})`}
                  </Badge>
                ))}
              </div>
            </div>

            {/* Conflicts Warning */}
            {conflicts.length > 0 && (
              <div className="p-4 bg-amber-50 border border-amber-200 rounded-lg dark:bg-amber-950/20 dark:border-amber-800">
                <div className="flex items-center gap-2 text-amber-800 dark:text-amber-200 mb-2">
                  <AlertCircle className="h-5 w-5" />
                  <span className="font-medium">{conflicts.length} Part Conflict(s) Detected</span>
                </div>
                <p className="text-sm text-amber-700 dark:text-amber-300 mb-2">
                  Some parts have different descriptions than what's in your catalog.
                </p>
                <Button size="sm" variant="outline" onClick={() => setShowConflictDialog(true)}>
                  Review Conflicts
                </Button>
              </div>
            )}

            {/* Line Items */}
            <div>
              <h3 className="font-medium mb-2">
                Line Items ({parseResult.order.line_items.length})
              </h3>
              <div className="max-h-64 overflow-auto border rounded-lg">
                <table className="w-full text-sm min-w-[500px]">
                  <thead className="bg-muted sticky top-0">
                    <tr>
                      <th className="text-left p-2 whitespace-nowrap">Part Number</th>
                      <th className="text-left p-2">Description</th>
                      <th className="text-left p-2 whitespace-nowrap">Location</th>
                      <th className="text-center p-2 whitespace-nowrap">Qty/Unit</th>
                      <th className="text-center p-2 whitespace-nowrap">Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {parseResult.order.line_items.slice(0, 50).map((item, i) => (
                      <tr key={i} className="border-t">
                        <td className="p-2 font-mono whitespace-nowrap">{item.part_number}</td>
                        <td className="p-2 text-muted-foreground max-w-[200px] truncate">
                          {item.description || '-'}
                        </td>
                        <td className="p-2 whitespace-nowrap">{item.location || '-'}</td>
                        <td className="p-2 text-center">{item.qty_per_unit}</td>
                        <td className="p-2 text-center">{item.total_qty_needed}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
                {parseResult.order.line_items.length > 50 && (
                  <p className="p-2 text-center text-muted-foreground">
                    ...and {parseResult.order.line_items.length - 50} more items
                  </p>
                )}
              </div>
              <p className="text-xs text-muted-foreground mt-1 sm:hidden">
                ← Scroll horizontally to see all columns →
              </p>
            </div>

            {/* Options */}
            <div className="flex items-center gap-4 pt-4 border-t">
              <label className="flex items-center gap-2 text-sm cursor-pointer">
                <input
                  type="checkbox"
                  checked={saveToCatalog}
                  onChange={(e) => setSaveToCatalog(e.target.checked)}
                  className="rounded border-gray-300"
                />
                <Database className="h-4 w-4 text-muted-foreground" />
                <span>Save parts to catalog</span>
              </label>
              {catalogParts.length > 0 && (
                <span className="text-xs text-muted-foreground">
                  ({catalogParts.length} parts in catalog)
                </span>
              )}
            </div>

            {/* Actions */}
            <div className="flex justify-end gap-2 pt-4">
              <Button variant="outline" onClick={clearResult}>
                Cancel
              </Button>
              <Button onClick={handleImport} disabled={isImporting}>
                {isImporting ? 'Importing...' : 'Import Order'}
              </Button>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Template Download */}
      <Card>
        <CardHeader>
          <CardTitle>Download Template</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-muted-foreground mb-4">
            Download an Excel template to get started. Choose the format that fits your order:
          </p>
          <div className="flex flex-wrap gap-2">
            <Button variant="outline" onClick={() => downloadImportTemplate('single')}>
              <Download className="mr-2 h-4 w-4" />
              Single Tool Type
            </Button>
            <Button variant="outline" onClick={() => downloadImportTemplate('multi')}>
              <Download className="mr-2 h-4 w-4" />
              Multiple Tool Types
            </Button>
          </div>
          <p className="text-xs text-muted-foreground mt-3">
            <strong>Single Tool Type:</strong> All tools share the same parts list (e.g., 5x identical 230Q units).
            <br />
            <strong>Multiple Tool Types:</strong> Different tools have different BOMs (e.g., 2x 230Q + 1x 450Q).
          </p>
        </CardContent>
      </Card>

      {/* Help */}
      <Card>
        <CardHeader>
          <CardTitle>File Format Guide</CardTitle>
        </CardHeader>
        <CardContent className="space-y-4 text-sm">
          <div>
            <h4 className="font-medium mb-1">Single Tool Type (Simple Format)</h4>
            <p className="text-muted-foreground">
              Excel file with "Order Info" sheet containing SO Number, PO Number, Customer, Tool Qty, Tool Model.
              "Parts" sheet with Part Number, Description, Location, Qty/Unit columns.
            </p>
          </div>
          <div>
            <h4 className="font-medium mb-1">Multiple Tool Types (Advanced Format)</h4>
            <p className="text-muted-foreground">
              "Order Info" sheet for header info, then separate sheets for each tool type (e.g., "230Q", "450Q").
              Each tool type sheet has its own parts list with a Qty column for number of tools of that type.
            </p>
          </div>
          <div>
            <h4 className="font-medium mb-1">Legacy Format</h4>
            <p className="text-muted-foreground">
              Single sheet with tool columns (e.g., "3137-1", "3137-2") for each tool's quantities.
              The importer auto-detects this format and creates tools accordingly.
            </p>
          </div>
          <div>
            <h4 className="font-medium mb-1">Expected Columns</h4>
            <ul className="list-disc list-inside text-muted-foreground">
              <li>Part Number (required)</li>
              <li>Description (optional)</li>
              <li>Location/Bin (optional)</li>
              <li>Quantity per unit or tool-specific quantities</li>
            </ul>
          </div>
        </CardContent>
      </Card>

      {/* Duplicate Parts Dialog */}
      <DuplicatePartsDialog
        open={showConflictDialog}
        onOpenChange={setShowConflictDialog}
        conflicts={conflicts}
        onResolve={handleConflictResolve}
      />

      {/* Template Select Dialog */}
      <TemplateSelectDialog
        open={showTemplateDialog}
        onOpenChange={setShowTemplateDialog}
        onSelect={handleTemplateSelect}
      />
    </div>
  );
}

// src/app/pages/import/import.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { Subscription } from 'rxjs';
import { OrdersService } from '../../services/orders.service';
import { ExcelService } from '../../services/excel.service';
import { PartsCatalogService } from '../../services/parts-catalog.service';
import { BomTemplatesService } from '../../services/bom-templates.service';
import { ImportedOrder, ImportedLineItem, PartConflict, BOMTemplateWithItems } from '../../models';
import { TemplateSelectDialogComponent } from '../../components/dialogs/template-select-dialog.component';
import { DuplicatePartsDialogComponent } from '../../components/dialogs/duplicate-parts-dialog.component';

@Component({
  selector: 'app-import',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, TemplateSelectDialogComponent, DuplicatePartsDialogComponent],
  template: `
    <div>
      <div class="mb-4">
        <h1 class="h3 fw-bold mb-1">Import Order</h1>
        <p class="text-muted mb-0">Upload an Excel or CSV file to import a sales order</p>
      </div>

      <!-- Drop Zone -->
      <div class="card mb-4" *ngIf="!parseResult">
        <div class="card-body">
          <div class="dropzone"
               [class.dragover]="isDragging"
               (drop)="onDrop($event)"
               (dragover)="onDragOver($event)"
               (dragleave)="onDragLeave($event)">
            <i class="bi bi-upload display-4 text-muted mb-3"></i>
            <p class="h5 mb-2">Drag and drop your file here</p>
            <p class="text-muted mb-4">Supports Excel (.xlsx) and CSV files</p>
            <div class="d-flex justify-content-center gap-2 flex-wrap">
              <label class="btn btn-primary">
                <i class="bi bi-file-earmark-spreadsheet me-1"></i>
                Browse Files
                <input type="file" class="d-none" accept=".xlsx,.xls,.csv" (change)="onFileSelect($event)">
              </label>
              <button class="btn btn-outline-secondary" (click)="showTemplateDialog = true">
                <i class="bi bi-file-earmark-text me-1"></i>
                Load from Template
              </button>
            </div>
          </div>

          <!-- Parse Errors -->
          <div class="alert alert-danger mt-4" *ngIf="parseErrors.length > 0">
            <div class="d-flex align-items-center mb-2">
              <i class="bi bi-exclamation-circle me-2"></i>
              <strong>Import Failed</strong>
            </div>
            <ul class="mb-0 ps-3">
              <li *ngFor="let error of parseErrors">{{ error }}</li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Preview -->
      <div class="card mb-4" *ngIf="parseResult">
        <div class="card-header d-flex justify-content-between align-items-center">
          <div class="d-flex align-items-center">
            <i class="bi bi-check-circle-fill text-success me-2"></i>
            <span class="fw-semibold">Preview: SO-{{ parseResult.order.so_number }}</span>
            <span *ngIf="loadedFromTemplate" class="badge bg-info ms-2">From Template</span>
          </div>
          <button class="btn btn-sm btn-outline-secondary" (click)="clearResult()">
            <i class="bi bi-x-lg"></i>
          </button>
        </div>
        <div class="card-body">
          <!-- Warnings -->
          <div class="alert alert-warning" *ngIf="parseResult.warnings.length > 0">
            <strong>Warnings</strong>
            <ul class="mb-0 ps-3">
              <li *ngFor="let warning of parseResult.warnings">{{ warning }}</li>
            </ul>
          </div>

          <!-- Conflicts detected -->
          <div class="alert alert-warning d-flex align-items-center justify-content-between" *ngIf="partConflicts.length > 0">
            <div>
              <i class="bi bi-exclamation-triangle me-2"></i>
              <strong>{{ partConflicts.length }} part(s)</strong> have different values than the Parts Catalog.
            </div>
            <button class="btn btn-sm btn-warning" (click)="showDuplicatesDialog = true">
              Review Conflicts
            </button>
          </div>

          <!-- Order Info -->
          <div class="mb-4">
            <h6 class="fw-semibold mb-2">Order Details</h6>
            <div class="row g-3 small">
              <div class="col-6 col-md-3">
                <label class="form-label text-muted small mb-1">SO Number *</label>
                <input type="text" class="form-control form-control-sm" [(ngModel)]="parseResult.order.so_number">
              </div>
              <div class="col-6 col-md-3">
                <label class="form-label text-muted small mb-1">PO Number</label>
                <input type="text" class="form-control form-control-sm" [(ngModel)]="parseResult.order.po_number">
              </div>
              <div class="col-6 col-md-3">
                <label class="form-label text-muted small mb-1">Customer</label>
                <input type="text" class="form-control form-control-sm" [(ngModel)]="parseResult.order.customer_name">
              </div>
              <div class="col-6 col-md-3">
                <label class="form-label text-muted small mb-1">Due Date</label>
                <input type="date" class="form-control form-control-sm" [(ngModel)]="parseResult.order.due_date">
              </div>
            </div>
          </div>

          <!-- Tools -->
          <div class="mb-4">
            <div class="d-flex justify-content-between align-items-center mb-2">
              <h6 class="fw-semibold mb-0">Tools ({{ parseResult.order.tools.length }})</h6>
              <div class="d-flex align-items-center gap-2">
                <label class="form-label mb-0 small text-muted">Tool Count:</label>
                <input
                  type="number"
                  class="form-control form-control-sm"
                  style="width: 70px;"
                  [(ngModel)]="toolCount"
                  [min]="1"
                  (change)="regenerateTools()"
                >
              </div>
            </div>
            <div class="d-flex flex-wrap gap-2">
              <span *ngFor="let tool of parseResult.order.tools" class="badge bg-secondary">
                {{ tool.tool_number }}
                <span *ngIf="tool.tool_model"> [{{ tool.tool_model }}]</span>
              </span>
            </div>
          </div>

          <!-- Line Items -->
          <div class="mb-4">
            <h6 class="fw-semibold mb-2">Line Items ({{ parseResult.order.line_items.length }})</h6>
            <div class="table-responsive border rounded" style="max-height: 300px; overflow-y: auto;">
              <table class="table table-sm mb-0">
                <thead class="table-secondary sticky-top">
                  <tr>
                    <th>Part Number</th>
                    <th>Description</th>
                    <th>Location</th>
                    <th class="text-center">Qty/Unit</th>
                    <th class="text-center">Total</th>
                  </tr>
                </thead>
                <tbody>
                  <tr *ngFor="let item of parseResult.order.line_items.slice(0, 50)">
                    <td class="font-mono">{{ item.part_number }}</td>
                    <td class="text-muted">{{ item.description || '-' }}</td>
                    <td>{{ item.location || '-' }}</td>
                    <td class="text-center">{{ item.qty_per_unit }}</td>
                    <td class="text-center">{{ item.total_qty_needed }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
            <p class="small text-muted text-center mt-2" *ngIf="parseResult.order.line_items.length > 50">
              ...and {{ parseResult.order.line_items.length - 50 }} more items
            </p>
          </div>

          <!-- Import Options -->
          <div class="mb-4 p-3 bg-body-secondary rounded">
            <h6 class="fw-semibold mb-2">Import Options</h6>
            <div class="form-check">
              <input class="form-check-input" type="checkbox" id="saveToCatalog" [(ngModel)]="saveToCatalog">
              <label class="form-check-label" for="saveToCatalog">
                Save new parts to Parts Catalog
                <span class="text-muted small d-block">Parts not already in the catalog will be added automatically</span>
              </label>
            </div>
            <div class="form-check mt-2">
              <input class="form-check-input" type="checkbox" id="useLegacyFormat" [(ngModel)]="useLegacyFormat"
                     (change)="reparse()">
              <label class="form-check-label" for="useLegacyFormat">
                Legacy format (tool columns)
                <span class="text-muted small d-block">Enable if your file has columns like "3137-1", "3137-2" for per-tool quantities</span>
              </label>
            </div>
          </div>

          <!-- Actions -->
          <div class="d-flex justify-content-end gap-2">
            <button class="btn btn-outline-secondary" (click)="clearResult()">Cancel</button>
            <button class="btn btn-primary" (click)="handleImport()" [disabled]="isImporting || !parseResult.order.so_number">
              <i class="bi me-1" [class]="isImporting ? 'bi-arrow-clockwise spin' : 'bi-check-circle'"></i>
              {{ isImporting ? 'Importing...' : 'Import Order' }}
            </button>
          </div>
        </div>
      </div>

      <!-- Template Download -->
      <div class="card mb-4">
        <div class="card-header">
          <span class="fw-semibold">Download Template</span>
        </div>
        <div class="card-body">
          <p class="small text-muted mb-3">Download an Excel template to get started:</p>
          <div class="d-flex flex-wrap gap-2">
            <button class="btn btn-outline-secondary" (click)="downloadTemplate('single')">
              <i class="bi bi-download me-1"></i> Single Tool Type
            </button>
            <button class="btn btn-outline-secondary" (click)="downloadTemplate('multi')">
              <i class="bi bi-download me-1"></i> Multiple Tool Types
            </button>
          </div>
          <p class="small text-muted mt-3 mb-0">
            <strong>Single Tool Type:</strong> All tools share the same parts list.<br>
            <strong>Multiple Tool Types:</strong> Different tools have different BOMs.
          </p>
        </div>
      </div>

      <!-- Help -->
      <div class="card">
        <div class="card-header">
          <span class="fw-semibold">File Format Guide</span>
        </div>
        <div class="card-body">
          <div class="mb-3">
            <h6 class="fw-semibold">Single Tool Type (Simple Format)</h6>
            <p class="small text-muted mb-0">
              Excel file with "Order Info" sheet containing SO Number, PO Number, Customer, Tool Qty, Tool Model.
              "Parts" sheet with Part Number, Description, Location, Qty/Unit columns.
            </p>
          </div>
          <div class="mb-3">
            <h6 class="fw-semibold">Legacy Format (Tool Columns)</h6>
            <p class="small text-muted mb-0">
              Excel file with columns named like "3137-1", "3137-2" for per-tool quantities.
              Enable "Legacy format" option to use this format.
            </p>
          </div>
          <div class="mb-3">
            <h6 class="fw-semibold">Expected Columns</h6>
            <ul class="small text-muted mb-0">
              <li>Part Number (required)</li>
              <li>Description (optional)</li>
              <li>Location/Bin (optional)</li>
              <li>Quantity per unit or tool-specific quantities</li>
            </ul>
          </div>
        </div>
      </div>

      <!-- Template Select Dialog -->
      <app-template-select-dialog
        [(show)]="showTemplateDialog"
        (templateSelected)="handleTemplateSelected($event)"
      ></app-template-select-dialog>

      <!-- Duplicate Parts Dialog -->
      <app-duplicate-parts-dialog
        [(show)]="showDuplicatesDialog"
        [conflicts]="partConflicts"
        (resolved)="handleConflictsResolved($event)"
      ></app-duplicate-parts-dialog>
    </div>
  `,
  styles: [`
    .dropzone {
      border: 2px dashed var(--bs-border-color);
      border-radius: 0.5rem;
      padding: 3rem;
      text-align: center;
      transition: all 0.2s ease;
    }

    .dropzone.dragover {
      border-color: #0d6efd;
      background-color: rgba(13, 110, 253, 0.05);
    }

    .dropzone:hover {
      border-color: var(--bs-secondary-color);
    }

    .font-mono {
      font-family: monospace;
    }

    .spin {
      animation: spin 1s linear infinite;
    }

    @keyframes spin {
      from { transform: rotate(0deg); }
      to { transform: rotate(360deg); }
    }

    .sticky-top {
      position: sticky;
      top: 0;
      z-index: 1;
    }
  `]
})
export class ImportComponent implements OnInit, OnDestroy {
  isDragging = false;
  parseResult: {
    order: ImportedOrder;
    errors: string[];
    warnings: string[];
  } | null = null;
  parseErrors: string[] = [];
  isImporting = false;
  loadedFromTemplate = false;

  // Dialogs
  showTemplateDialog = false;
  showDuplicatesDialog = false;

  // Conflicts
  partConflicts: PartConflict[] = [];

  // Import options
  saveToCatalog = true;
  useLegacyFormat = false;
  toolCount = 1;

  // File reference for re-parsing
  private currentFile: File | null = null;

  private subscriptions: Subscription[] = [];

  constructor(
    private router: Router,
    private ordersService: OrdersService,
    private excelService: ExcelService,
    private partsCatalogService: PartsCatalogService,
    private bomTemplatesService: BomTemplatesService
  ) {}

  ngOnInit(): void {
    // Preload parts catalog for conflict detection
    this.partsCatalogService.fetchParts();
  }

  ngOnDestroy(): void {
    this.subscriptions.forEach(sub => sub.unsubscribe());
  }

  onDragOver(event: DragEvent): void {
    event.preventDefault();
    this.isDragging = true;
  }

  onDragLeave(event: DragEvent): void {
    event.preventDefault();
    this.isDragging = false;
  }

  onDrop(event: DragEvent): void {
    event.preventDefault();
    this.isDragging = false;
    const file = event.dataTransfer?.files[0];
    if (file) {
      this.handleFile(file);
    }
  }

  onFileSelect(event: Event): void {
    const input = event.target as HTMLInputElement;
    const file = input.files?.[0];
    if (file) {
      this.handleFile(file);
    }
  }

  async handleFile(file: File): Promise<void> {
    this.parseResult = null;
    this.parseErrors = [];
    this.partConflicts = [];
    this.loadedFromTemplate = false;
    this.currentFile = file;

    const isExcel = file.name.endsWith('.xlsx') || file.name.endsWith('.xls') || file.type.includes('spreadsheet');
    const isCsv = file.name.endsWith('.csv') || file.type === 'text/csv';

    if (!isExcel && !isCsv) {
      this.parseErrors = ['Please upload an Excel (.xlsx) or CSV file'];
      return;
    }

    let result;
    if (isExcel) {
      result = this.useLegacyFormat
        ? await this.excelService.parseEnhancedExcelFileWithLegacySupport(file)
        : await this.excelService.parseEnhancedExcelFile(file);
    } else {
      result = await this.excelService.parseCsvFile(file);
    }

    if (result.success && result.order) {
      this.parseResult = {
        order: result.order,
        errors: result.errors,
        warnings: result.warnings,
      };
      this.toolCount = result.order.tools.length;

      // Check for conflicts with parts catalog
      this.checkForConflicts(result.order.line_items);
    } else {
      this.parseErrors = result.errors;
    }
  }

  async reparse(): Promise<void> {
    if (this.currentFile) {
      await this.handleFile(this.currentFile);
    }
  }

  checkForConflicts(lineItems: ImportedLineItem[]): void {
    this.partConflicts = this.partsCatalogService.checkForConflicts(lineItems);
  }

  regenerateTools(): void {
    if (!this.parseResult) return;

    const soNumber = this.parseResult.order.so_number;
    const toolModel = this.parseResult.order.tools[0]?.tool_model;
    const count = Math.max(1, this.toolCount);

    this.parseResult.order.tools = [];
    for (let i = 1; i <= count; i++) {
      this.parseResult.order.tools.push({
        tool_number: `${soNumber}-${i}`,
        tool_model: toolModel,
      });
    }

    // Recalculate total_qty_needed for all line items
    for (const item of this.parseResult.order.line_items) {
      item.total_qty_needed = item.qty_per_unit * count;
    }
  }

  handleTemplateSelected(template: BOMTemplateWithItems): void {
    // Create a new order from the template
    const order: ImportedOrder = {
      so_number: '',
      tools: [{
        tool_number: '-1',
        tool_model: template.tool_model || undefined,
      }],
      line_items: template.items.map(item => ({
        part_number: item.part_number,
        description: item.description || undefined,
        location: item.location || undefined,
        qty_per_unit: item.qty_per_unit,
        total_qty_needed: item.qty_per_unit,
      })),
    };

    this.parseResult = {
      order,
      errors: [],
      warnings: [`Loaded from template: ${template.name}`],
    };
    this.loadedFromTemplate = true;
    this.toolCount = 1;
    this.currentFile = null;

    // Check for conflicts
    this.checkForConflicts(order.line_items);
  }

  async handleConflictsResolved(conflicts: PartConflict[]): Promise<void> {
    // Apply resolutions to the parts catalog
    await this.partsCatalogService.applyConflictResolutions(conflicts);

    // Clear conflicts
    this.partConflicts = [];
  }

  async handleImport(): Promise<void> {
    if (!this.parseResult?.order) return;

    this.isImporting = true;

    // Save new parts to catalog if enabled
    if (this.saveToCatalog) {
      await this.partsCatalogService.savePartsFromImport(
        this.parseResult.order.line_items,
        true // Skip existing parts
      );
    }

    // Import the order
    const result = await this.ordersService.importOrder(this.parseResult.order);
    this.isImporting = false;

    if (result) {
      this.router.navigate(['/orders', result.id]);
    }
  }

  clearResult(): void {
    this.parseResult = null;
    this.parseErrors = [];
    this.partConflicts = [];
    this.loadedFromTemplate = false;
    this.currentFile = null;
  }

  downloadTemplate(type: 'single' | 'multi'): void {
    this.excelService.downloadImportTemplate(type);
  }
}
