// src/components/NamePrompt.tsx
import { useState, useEffect } from 'react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { useSettings } from '@/hooks/useSettings';
import { User } from 'lucide-react';

export function NamePrompt() {
  const { settings, loaded, updateSettings } = useSettings();
  const [open, setOpen] = useState(false);
  const [name, setName] = useState('');

  useEffect(() => {
    // Show the dialog if settings are loaded and no name is set
    if (loaded && !settings.user_name) {
      setOpen(true);
    }
  }, [loaded, settings.user_name]);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (name.trim()) {
      updateSettings({ user_name: name.trim() });
      setOpen(false);
    }
  };

  // Don't render anything until settings are loaded
  if (!loaded) return null;

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogContent className="sm:max-w-md" onPointerDownOutside={(e) => e.preventDefault()}>
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <User className="h-5 w-5" />
            Welcome! What's your name?
          </DialogTitle>
          <DialogDescription>
            Your name will be recorded with any picks or changes you make,
            so the team can see who did what.
          </DialogDescription>
        </DialogHeader>
        <form onSubmit={handleSubmit}>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="name">Your Name</Label>
              <Input
                id="name"
                placeholder="Enter your name"
                value={name}
                onChange={(e) => setName(e.target.value)}
                autoFocus
                autoComplete="name"
              />
            </div>
          </div>
          <DialogFooter>
            <Button type="submit" disabled={!name.trim()}>
              Continue
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  );
}

// AngularBootstrap/src/app/components/auth/name-prompt.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { SettingsService } from '../../services/settings.service';

@Component({
  selector: 'app-name-prompt',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div *ngIf="showPrompt" class="modal fade show d-block" tabindex="-1" style="background-color: rgba(0,0,0,0.5);">
      <div class="modal-dialog modal-dialog-centered" style="max-width: 400px;">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title d-flex align-items-center gap-2">
              <i class="bi bi-person-fill"></i>
              Welcome! What's your name?
            </h5>
          </div>
          <form (ngSubmit)="handleSubmit()">
            <div class="modal-body">
              <p class="text-muted mb-3">
                Your name will be recorded with any picks or changes you make,
                so the team can see who did what.
              </p>
              <div class="mb-3">
                <label for="userName" class="form-label">Your Name</label>
                <input
                  id="userName"
                  type="text"
                  class="form-control"
                  placeholder="Enter your name"
                  [(ngModel)]="name"
                  name="userName"
                  autofocus
                  autocomplete="name"
                >
              </div>
            </div>
            <div class="modal-footer">
              <button type="submit" class="btn btn-primary" [disabled]="!name.trim()">
                Continue
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  `
})
export class NamePromptComponent implements OnInit {
  showPrompt = false;
  name = '';

  constructor(private settingsService: SettingsService) {}

  ngOnInit(): void {
    if (!this.settingsService.getUserName()) {
      this.showPrompt = true;
    }
  }

  handleSubmit(): void {
    if (this.name.trim()) {
      this.settingsService.setUserName(this.name.trim());
      this.showPrompt = false;
    }
  }
}
