// src/app/components/parts/bom-editor.component.ts
import { Component, Input, OnInit, EventEmitter, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgbModal } from '@ng-bootstrap/ng-bootstrap';
import { PartsService, Part } from '../../services/parts.service';
import { PartRelationshipsService, PartRelationship, CircularReferenceWarning } from '../../services/part-relationships.service';

@Component({
  selector: 'app-bom-editor',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './bom-editor.component.html',
  styles: [`
    .min-w-0 { min-width: 0; }
    .btn-ghost-danger {
      color: var(--bs-danger);
      background-color: transparent;
      border: none;
    }
    .btn-ghost-danger:hover {
      background-color: rgba(var(--bs-danger-rgb), 0.1);
    }
  `]
})
export class BOMEditorComponent implements OnInit {
  @Input() partId: string = '';
  @Output() update = new EventEmitter<void>();

  children: (PartRelationship & { part: Part })[] = [];
  availableParts: Part[] = [];
  loading = true;
  showAddDialog = false;
  showCircularWarning = false;
  circularWarningMessage = '';
  pendingChildId: string | null = null;

  newChild = {
    childId: '',
    quantity: 1,
    referenceDesignator: '',
    notes: ''
  };

  constructor(
    private partsService: PartsService,
    private relationshipsService: PartRelationshipsService
  ) {}

  async ngOnInit(): Promise<void> {
    await this.loadPart();
    await this.loadAvailableParts();
  }

  async loadPart(): Promise<void> {
    this.loading = true;
    const data = await this.partsService.getPartWithRelationships(this.partId);
    if (data && data.children) {
      this.children = data.children.sort((a: any, b: any) => a.sort_order - b.sort_order);
    }
    this.loading = false;
  }

  async loadAvailableParts(): Promise<void> {
    this.partsService.parts$.subscribe(parts => {
      this.availableParts = parts.filter(p => p.id !== this.partId);
    });
  }

  async addChild(): Promise<void> {
    if (!this.newChild.childId) return;

    const circularCheck = await this.relationshipsService.checkCircularReference(
      this.partId,
      this.newChild.childId
    );

    if (circularCheck.would_cycle) {
      this.circularWarningMessage = circularCheck.message;
      this.pendingChildId = this.newChild.childId;
      this.showCircularWarning = true;
      return;
    }

    await this.createRelationship(false);
  }

  async confirmCircular(): Promise<void> {
    await this.createRelationship(true);
    this.showCircularWarning = false;
    this.pendingChildId = null;
  }

  async createRelationship(skipCheck: boolean): Promise<void> {
    try {
      await this.relationshipsService.createRelationship(
        this.partId,
        this.newChild.childId,
        this.newChild.quantity,
        {
          referenceDesignator: this.newChild.referenceDesignator || undefined,
          notes: this.newChild.notes || undefined,
          skipCircularCheck: skipCheck
        }
      );

      this.newChild = { childId: '', quantity: 1, referenceDesignator: '', notes: '' };
      this.showAddDialog = false;
      await this.loadPart();
      this.update.emit();
    } catch (err) {
      console.error('Error creating relationship:', err);
    }
  }

  async updateQuantity(relationshipId: string, quantity: number): Promise<void> {
    await this.relationshipsService.updateRelationship(relationshipId, { quantity });
    await this.loadPart();
    this.update.emit();
  }

  async deleteChild(relationshipId: string): Promise<void> {
    if (confirm('Are you sure you want to remove this part from the BOM?')) {
      await this.relationshipsService.deleteRelationship(relationshipId);
      await this.loadPart();
      this.update.emit();
    }
  }
}

<div class="card">
  <div class="card-header d-flex justify-content-between align-items-center">
    <h6 class="mb-0">Bill of Materials ({{ children.length }})</h6>
    <button class="btn btn-sm btn-primary" (click)="showAddDialog = true">
      <i class="bi bi-plus-lg me-1"></i> Add Part
    </button>
  </div>
  <div class="card-body">
    <div *ngIf="loading" class="text-center py-4">
      <div class="spinner-border spinner-border-sm" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
    </div>

    <div *ngIf="!loading && children.length === 0" class="text-center py-4 text-muted">
      <p>No parts in this assembly yet.</p>
      <button class="btn btn-sm btn-outline-primary mt-2" (click)="showAddDialog = true">
        Add First Part
      </button>
    </div>

    <div *ngIf="!loading && children.length > 0" class="list-group">
      <div *ngFor="let rel of children" class="list-group-item">
        <div class="d-flex align-items-center gap-3">
          <i class="bi bi-grip-vertical text-muted"></i>
          <div class="flex-grow-1">
            <div class="d-flex align-items-center gap-2">
              <span class="font-monospace fw-medium">{{ rel.part.part_number }}</span>
              <span *ngIf="rel.reference_designator" class="text-muted small">({{ rel.reference_designator }})</span>
            </div>
            <div *ngIf="rel.part.description" class="small text-muted">{{ rel.part.description }}</div>
            <div *ngIf="rel.notes" class="small text-muted">Note: {{ rel.notes }}</div>
          </div>
          <div class="d-flex align-items-center gap-2">
            <label class="small text-muted mb-0">Qty:</label>
            <input type="number" class="form-control form-control-sm" style="width: 80px;" min="1"
                   [(ngModel)]="rel.quantity" (change)="updateQuantity(rel.id, rel.quantity)" />
            <button class="btn btn-sm btn-ghost-danger" (click)="deleteChild(rel.id)">
              <i class="bi bi-trash"></i>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Add Dialog -->
<div *ngIf="showAddDialog" class="modal d-block" tabindex="-1" style="background: rgba(0,0,0,0.5);">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add Part to BOM</h5>
        <button type="button" class="btn-close" (click)="showAddDialog = false"></button>
      </div>
      <div class="modal-body">
        <div class="mb-3">
          <label class="form-label">Part *</label>
          <select class="form-select" [(ngModel)]="newChild.childId">
            <option value="">Select a part</option>
            <option *ngFor="let part of availableParts" [value]="part.id">
              {{ part.part_number }}{{ part.description ? ' - ' + part.description : '' }}
            </option>
          </select>
        </div>
        <div class="row">
          <div class="col-6">
            <label class="form-label">Quantity *</label>
            <input type="number" class="form-control" min="1" [(ngModel)]="newChild.quantity" />
          </div>
          <div class="col-6">
            <label class="form-label">Reference Designator</label>
            <input type="text" class="form-control" placeholder="e.g., R1, C2" [(ngModel)]="newChild.referenceDesignator" />
          </div>
        </div>
        <div class="mt-3">
          <label class="form-label">Notes</label>
          <input type="text" class="form-control" placeholder="Optional notes" [(ngModel)]="newChild.notes" />
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" (click)="showAddDialog = false">Cancel</button>
        <button type="button" class="btn btn-primary" [disabled]="!newChild.childId" (click)="addChild()">
          Add Part
        </button>
      </div>
    </div>
  </div>
</div>

<!-- Circular Warning -->
<div *ngIf="showCircularWarning" class="modal d-block" tabindex="-1" style="background: rgba(0,0,0,0.5);">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header bg-warning bg-opacity-10">
        <h5 class="modal-title text-warning">
          <i class="bi bi-exclamation-triangle me-2"></i>Circular Reference Warning
        </h5>
        <button type="button" class="btn-close" (click)="showCircularWarning = false"></button>
      </div>
      <div class="modal-body">
        <p>{{ circularWarningMessage }}</p>
        <p class="text-muted small">
          Do you want to proceed anyway? This may cause issues with BOM explosion and inventory tracking.
        </p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" (click)="showCircularWarning = false">Cancel</button>
        <button type="button" class="btn btn-danger" (click)="confirmCircular()">Add Anyway</button>
      </div>
    </div>
  </div>
</div>

// src/components/parts/BOMEditor.tsx
import { useState, useEffect } from 'react';
import { Plus, Trash2, GripVertical, AlertCircle } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
  DialogDescription,
} from '@/components/ui/dialog';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { useParts } from '@/hooks/useParts';
import { usePartRelationships } from '@/hooks/usePartRelationships';
import type { PartWithRelationships, Part } from '@/types';

interface BOMEditorProps {
  partId: string;
  onUpdate?: () => void;
}

export function BOMEditor({ partId, onUpdate }: BOMEditorProps) {
  const { parts, getPartWithRelationships } = useParts();
  const {
    createRelationship,
    updateRelationship,
    deleteRelationship,
    checkCircularReference,
  } = usePartRelationships();
  const [part, setPart] = useState<PartWithRelationships | null>(null);
  const [loading, setLoading] = useState(true);
  const [showAddDialog, setShowAddDialog] = useState(false);
  const [showCircularWarning, setShowCircularWarning] = useState(false);
  const [circularWarningMessage, setCircularWarningMessage] = useState('');
  const [pendingChildId, setPendingChildId] = useState<string | null>(null);
  const [newChild, setNewChild] = useState({
    childId: '',
    quantity: '1',
    referenceDesignator: '',
    notes: '',
  });

  useEffect(() => {
    loadPart();
  }, [partId]);

  async function loadPart() {
    setLoading(true);
    const data = await getPartWithRelationships(partId);
    setPart(data);
    setLoading(false);
  }

  async function handleAddChild() {
    if (!newChild.childId) return;

    // Check for circular reference
    const circularCheck = await checkCircularReference(partId, newChild.childId);
    if (circularCheck.would_cycle) {
      setCircularWarningMessage(circularCheck.message);
      setPendingChildId(newChild.childId);
      setShowCircularWarning(true);
      return;
    }

    await createRelationship(
      partId,
      newChild.childId,
      parseInt(newChild.quantity) || 1,
      {
        referenceDesignator: newChild.referenceDesignator || undefined,
        notes: newChild.notes || undefined,
      }
    );

    setNewChild({
      childId: '',
      quantity: '1',
      referenceDesignator: '',
      notes: '',
    });
    setShowAddDialog(false);
    await loadPart();
    onUpdate?.();
  }

  async function handleConfirmCircular() {
    if (!pendingChildId) return;

    await createRelationship(
      partId,
      pendingChildId,
      parseInt(newChild.quantity) || 1,
      {
        referenceDesignator: newChild.referenceDesignator || undefined,
        notes: newChild.notes || undefined,
        skipCircularCheck: true,
      }
    );

    setNewChild({
      childId: '',
      quantity: '1',
      referenceDesignator: '',
      notes: '',
    });
    setShowAddDialog(false);
    setShowCircularWarning(false);
    setPendingChildId(null);
    await loadPart();
    onUpdate?.();
  }

  async function handleDeleteChild(relationshipId: string) {
    await deleteRelationship(relationshipId);
    await loadPart();
    onUpdate?.();
  }

  async function handleUpdateQuantity(relationshipId: string, quantity: number) {
    await updateRelationship(relationshipId, { quantity });
    await loadPart();
    onUpdate?.();
  }

  if (loading || !part) {
    return (
      <Card>
        <CardContent className="py-8 text-center">
          <p className="text-muted-foreground">Loading BOM...</p>
        </CardContent>
      </Card>
    );
  }

  const availableParts = parts.filter((p) => p.id !== partId);

  return (
    <>
      <Card>
        <CardHeader>
          <div className="flex items-center justify-between">
            <CardTitle>Bill of Materials ({part.children?.length || 0})</CardTitle>
            <Button size="sm" onClick={() => setShowAddDialog(true)}>
              <Plus className="mr-2 h-4 w-4" />
              Add Part
            </Button>
          </div>
        </CardHeader>
        <CardContent>
          {!part.children || part.children.length === 0 ? (
            <div className="text-center py-8 text-muted-foreground">
              <p>No parts in this assembly yet.</p>
              <Button
                variant="outline"
                size="sm"
                className="mt-4"
                onClick={() => setShowAddDialog(true)}
              >
                Add First Part
              </Button>
            </div>
          ) : (
            <div className="space-y-2">
              {part.children
                .sort((a, b) => a.sort_order - b.sort_order)
                .map((rel) => (
                  <div
                    key={rel.id}
                    className="flex items-center gap-3 p-3 border rounded hover:bg-accent"
                  >
                    <GripVertical className="h-4 w-4 text-muted-foreground flex-shrink-0" />
                    <div className="flex-1 min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="font-mono font-medium">{rel.part.part_number}</span>
                        {rel.reference_designator && (
                          <span className="text-sm text-muted-foreground">
                            ({rel.reference_designator})
                          </span>
                        )}
                      </div>
                      {rel.part.description && (
                        <div className="text-sm text-muted-foreground truncate">
                          {rel.part.description}
                        </div>
                      )}
                      {rel.notes && (
                        <div className="text-xs text-muted-foreground mt-1">
                          Note: {rel.notes}
                        </div>
                      )}
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <Label className="text-sm text-muted-foreground">Qty:</Label>
                      <Input
                        type="number"
                        min="1"
                        value={rel.quantity}
                        onChange={(e) =>
                          handleUpdateQuantity(rel.id, parseInt(e.target.value) || 1)
                        }
                        className="w-20"
                      />
                      <Button
                        variant="ghost"
                        size="icon"
                        onClick={() => handleDeleteChild(rel.id)}
                      >
                        <Trash2 className="h-4 w-4 text-destructive" />
                      </Button>
                    </div>
                  </div>
                ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Add Child Part Dialog */}
      <Dialog open={showAddDialog} onOpenChange={setShowAddDialog}>
        <DialogContent className="max-w-lg">
          <DialogHeader>
            <DialogTitle>Add Part to BOM</DialogTitle>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div className="space-y-2">
              <Label htmlFor="child_part">Part *</Label>
              <Select
                value={newChild.childId}
                onValueChange={(value) =>
                  setNewChild({ ...newChild, childId: value })
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder="Select a part" />
                </SelectTrigger>
                <SelectContent>
                  {availableParts.map((p) => (
                    <SelectItem key={p.id} value={p.id}>
                      {p.part_number}
                      {p.description && ` - ${p.description}`}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <Label htmlFor="quantity">Quantity *</Label>
                <Input
                  id="quantity"
                  type="number"
                  min="1"
                  value={newChild.quantity}
                  onChange={(e) =>
                    setNewChild({ ...newChild, quantity: e.target.value })
                  }
                />
              </div>
              <div className="space-y-2">
                <Label htmlFor="ref_designator">Reference Designator</Label>
                <Input
                  id="ref_designator"
                  placeholder="e.g., R1, C2"
                  value={newChild.referenceDesignator}
                  onChange={(e) =>
                    setNewChild({ ...newChild, referenceDesignator: e.target.value })
                  }
                />
              </div>
            </div>
            <div className="space-y-2">
              <Label htmlFor="notes">Notes</Label>
              <Input
                id="notes"
                placeholder="Optional notes"
                value={newChild.notes}
                onChange={(e) =>
                  setNewChild({ ...newChild, notes: e.target.value })
                }
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShowAddDialog(false)}>
              Cancel
            </Button>
            <Button onClick={handleAddChild} disabled={!newChild.childId}>
              Add Part
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      {/* Circular Reference Warning Dialog */}
      <Dialog open={showCircularWarning} onOpenChange={setShowCircularWarning}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2 text-amber-600 dark:text-amber-400">
              <AlertCircle className="h-5 w-5" />
              Circular Reference Warning
            </DialogTitle>
            <DialogDescription>
              {circularWarningMessage}
            </DialogDescription>
          </DialogHeader>
          <div className="py-4">
            <p className="text-sm text-muted-foreground">
              Do you want to proceed anyway? This may cause issues with BOM explosion and
              inventory tracking.
            </p>
          </div>
          <DialogFooter>
            <Button
              variant="outline"
              onClick={() => {
                setShowCircularWarning(false);
                setPendingChildId(null);
              }}
            >
              Cancel
            </Button>
            <Button variant="destructive" onClick={handleConfirmCircular}>
              Add Anyway
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
