// AngularBootstrap/src/app/components/parts/part-detail.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { NgbActiveModal } from '@ng-bootstrap/ng-bootstrap';
import { PartsService, Part, ClassificationType } from '../../services/parts.service';
import { ClassificationBadgeComponent } from './classification-badge.component';
import { BOMEditorComponent } from './bom-editor.component';
import { ModificationChainComponent } from './modification-chain.component';

@Component({
  selector: 'app-part-detail',
  standalone: true,
  imports: [CommonModule, FormsModule, ClassificationBadgeComponent, BOMEditorComponent, ModificationChainComponent],
  templateUrl: './part-detail.component.html'
})
export class PartDetailComponent implements OnInit {
  @Input() partId?: string;
  @Input() isNew = false;

  part: any = null;
  loading = true;
  isEditing = false;
  
  editForm = {
    part_number: '',
    description: '',
    classification_type: '' as ClassificationType | '',
    default_location: '',
    notes: ''
  };

  constructor(
    public activeModal: NgbActiveModal,
    private partsService: PartsService
  ) {}

  async ngOnInit(): Promise<void> {
    if (this.isNew) {
      this.isEditing = true;
      this.loading = false;
    } else if (this.partId) {
      await this.loadPart();
    }
  }

  async loadPart(): Promise<void> {
    this.loading = true;
    if (this.partId) {
      this.part = await this.partsService.getPartWithRelationships(this.partId);
      if (this.part) {
        this.editForm = {
          part_number: this.part.part_number,
          description: this.part.description || '',
          classification_type: this.part.classification_type || '',
          default_location: this.part.default_location || '',
          notes: this.part.notes || ''
        };
      }
    }
    this.loading = false;
  }

  async save(): Promise<void> {
    if (this.isNew) {
      await this.partsService.createPart({
        part_number: this.editForm.part_number.trim(),
        description: this.editForm.description.trim() || null,
        classification_type: this.editForm.classification_type || null,
        default_location: this.editForm.default_location.trim() || null,
        base_part_id: null,
        notes: this.editForm.notes.trim() || null
      });
      this.activeModal.close();
    } else if (this.partId) {
      await this.partsService.updatePart(this.partId, {
        part_number: this.editForm.part_number.trim(),
        description: this.editForm.description.trim() || null,
        classification_type: this.editForm.classification_type || null,
        default_location: this.editForm.default_location.trim() || null,
        notes: this.editForm.notes.trim() || null
      });
      await this.loadPart();
      this.isEditing = false;
    }
  }

  cancel(): void {
    if (this.isNew) {
      this.activeModal.dismiss();
    } else {
      this.isEditing = false;
      if (this.part) {
        this.editForm = {
          part_number: this.part.part_number,
          description: this.part.description || '',
          classification_type: this.part.classification_type || '',
          default_location: this.part.default_location || '',
          notes: this.part.notes || ''
        };
      }
    }
  }

  get isAssembly(): boolean {
    return this.part?.classification_type === 'assembly';
  }

  get isModified(): boolean {
    return this.part?.classification_type === 'modified';
  }

  getClassificationBadgeClass(type: ClassificationType): string {
    const classes: Record<ClassificationType, string> = {
      purchased: 'badge bg-primary',
      manufactured: 'badge bg-warning text-dark',
      assembly: 'badge bg-secondary',
      modified: 'badge bg-info text-dark'
    };
    return classes[type];
  }
}

<div class="modal-header">
  <h5 class="modal-title">{{ isNew ? 'Create New Part' : 'Part Details' }}</h5>
  <button type="button" class="btn-close" (click)="activeModal.dismiss()"></button>
</div>

<div class="modal-body" style="max-height: 80vh; overflow-y: auto;">
  <div *ngIf="loading" class="text-center py-5">
    <div class="spinner-border text-primary" role="status">
      <span class="visually-hidden">Loading...</span>
    </div>
  </div>

  <div *ngIf="!loading">
    <!-- Edit/View Toolbar -->
    <div class="d-flex justify-content-end mb-3" *ngIf="!isNew">
      <button *ngIf="!isEditing" class="btn btn-sm btn-outline-secondary" (click)="isEditing = true">
        <i class="bi bi-pencil me-1"></i> Edit
      </button>
      <div *ngIf="isEditing" class="btn-group btn-group-sm">
        <button class="btn btn-outline-secondary" (click)="cancel()">
          <i class="bi bi-x me-1"></i> Cancel
        </button>
        <button class="btn btn-primary" (click)="save()" [disabled]="!editForm.part_number.trim()">
          <i class="bi bi-check-lg me-1"></i> Save
        </button>
      </div>
    </div>

    <!-- Part Information -->
    <div class="card mb-3">
      <div class="card-header">
        <h6 class="mb-0">Part Information</h6>
      </div>
      <div class="card-body">
        <div *ngIf="isEditing">
          <div class="row g-3">
            <div class="col-md-6">
              <label class="form-label">Part Number *</label>
              <input type="text" class="form-control" [(ngModel)]="editForm.part_number" />
            </div>
            <div class="col-md-6">
              <label class="form-label">Classification</label>
              <select class="form-select" [(ngModel)]="editForm.classification_type">
                <option value="">Select classification</option>
                <option value="purchased">Purchased</option>
                <option value="manufactured">Manufactured</option>
              </select>
            </div>
            <div class="col-12">
              <label class="form-label d-block">Additional Attributes</label>
              <div class="form-check form-check-inline">
                <input
                  class="form-check-input"
                  type="checkbox"
                  id="assemblyCheck"
                  [(ngModel)]="editForm.is_assembly"
                  (change)="onAssemblyChange()"
                />
                <label class="form-check-label" for="assemblyCheck">
                  <i class="bi bi-boxes me-1"></i> Assembly
                </label>
              </div>
              <div class="form-check form-check-inline">
                <input
                  class="form-check-input"
                  type="checkbox"
                  id="modifiedCheck"
                  [(ngModel)]="editForm.is_modified"
                  (change)="onModifiedChange()"
                />
                <label class="form-check-label" for="modifiedCheck">
                  <i class="bi bi-wrench me-1"></i> Modified
                </label>
              </div>
            </div>
            <div class="col-12">
              <label class="form-label">Description</label>
              <input type="text" class="form-control" [(ngModel)]="editForm.description" />
            </div>
            <div class="col-12">
              <label class="form-label">Default Location</label>
              <input type="text" class="form-control" [(ngModel)]="editForm.default_location" />
            </div>
            <div class="col-12">
              <label class="form-label">Notes</label>
              <textarea class="form-control" rows="3" [(ngModel)]="editForm.notes"></textarea>
            </div>
          </div>
        </div>

        <div *ngIf="!isEditing && part">
          <div class="d-flex align-items-center gap-2 mb-2">
            <h4 class="mb-0 font-monospace">{{ part.part_number }}</h4>
            <app-classification-badge [classification]="part.classification_type"></app-classification-badge>
          </div>
          <div *ngIf="part.description" class="mb-2">
            <span class="text-muted">Description: </span>
            <span>{{ part.description }}</span>
          </div>
          <div *ngIf="part.default_location" class="mb-2">
            <span class="text-muted">Location: </span>
            <span class="fw-medium">📍 {{ part.default_location }}</span>
          </div>
          <div *ngIf="part.notes" class="mb-2">
            <span class="text-muted">Notes: </span>
            <span>{{ part.notes }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Base Part (for modified parts) -->
    <div *ngIf="!isNew && isModified && part?.base_part" class="card mb-3">
      <div class="card-header">
        <h6 class="mb-0">Based On</h6>
      </div>
      <div class="card-body">
        <div class="d-flex align-items-center gap-2">
          <i class="bi bi-box-seam text-muted"></i>
          <span class="font-monospace fw-medium">{{ part.base_part.part_number }}</span>
          <i class="bi bi-arrow-right text-muted"></i>
          <span class="font-monospace fw-medium">{{ part.part_number }}</span>
          <span *ngIf="part.base_part.description" class="text-muted small ms-2">
            ({{ part.base_part.description }})
          </span>
        </div>
      </div>
    </div>

    <!-- Modification Chain -->
    <div *ngIf="!isNew && (isModified || (part?.modifications && part.modifications.length > 0))">
      <app-modification-chain [partId]="partId!"></app-modification-chain>
    </div>

    <!-- BOM (for assemblies) -->
    <div *ngIf="!isNew && isAssembly" class="mt-3">
      <app-bom-editor [partId]="partId!" (update)="loadPart()"></app-bom-editor>
    </div>

    <!-- Where Used -->
    <div *ngIf="!isNew && part?.used_in && part.used_in.length > 0" class="card mt-3">
      <div class="card-header">
        <h6 class="mb-0">Where Used ({{ part.used_in.length }})</h6>
      </div>
      <div class="card-body">
        <div class="list-group">
          <div *ngFor="let rel of part.used_in" class="list-group-item">
            <div class="d-flex justify-content-between align-items-center">
              <div class="d-flex align-items-center gap-2">
                <i class="bi bi-box-seam text-muted"></i>
                <div>
                  <div class="font-monospace fw-medium">{{ rel.part.part_number }}</div>
                  <div *ngIf="rel.part.description" class="small text-muted">
                    {{ rel.part.description }}
                  </div>
                </div>
              </div>
              <div class="text-muted small">
                Qty: {{ rel.quantity }}
                <span *ngIf="rel.reference_designator" class="ms-2">({{ rel.reference_designator }})</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal-footer" *ngIf="isNew">
  <button type="button" class="btn btn-secondary" (click)="activeModal.dismiss()">Cancel</button>
  <button type="button" class="btn btn-primary" (click)="save()" [disabled]="!editForm.part_number.trim()">
    Create Part
  </button>
</div>

// src/components/parts/PartDetail.tsx
import { useState, useEffect } from 'react';
import { Edit2, Save, X, Package, ArrowRight } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { useParts } from '@/hooks/useParts';
import { cn } from '@/lib/utils';
import type { ClassificationType, PartWithRelationships } from '@/types';
import { BOMEditor } from './BOMEditor';
import { ModificationChain } from './ModificationChain';

interface PartDetailProps {
  partId: string;
  open: boolean;
  onClose: () => void;
}

function getClassificationColor(classification: ClassificationType | null): string {
  if (!classification) return 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200';

  switch (classification) {
    case 'purchased':
      return 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200';
    case 'manufactured':
      return 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200';
    case 'assembly':
      return 'bg-purple-100 text-purple-800 dark:bg-purple-900 dark:text-purple-200';
    case 'modified':
      return 'bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-200';
    default:
      return 'bg-gray-100 text-gray-800 dark:bg-gray-800 dark:text-gray-200';
  }
}

export function PartDetail({ partId, open, onClose }: PartDetailProps) {
  const { getPartWithRelationships, updatePart } = useParts();
  const [part, setPart] = useState<PartWithRelationships | null>(null);
  const [loading, setLoading] = useState(true);
  const [isEditing, setIsEditing] = useState(false);
  const [editForm, setEditForm] = useState({
    part_number: '',
    description: '',
    classification_type: '' as ClassificationType | '',
    default_location: '',
    notes: '',
  });

  useEffect(() => {
    if (open && partId) {
      loadPart();
    }
  }, [partId, open]);

  async function loadPart() {
    setLoading(true);
    const data = await getPartWithRelationships(partId);
    setPart(data);
    if (data) {
      setEditForm({
        part_number: data.part_number,
        description: data.description || '',
        classification_type: data.classification_type || '',
        default_location: data.default_location || '',
        notes: data.notes || '',
      });
    }
    setLoading(false);
  }

  async function handleSave() {
    if (!part) return;

    await updatePart(part.id, {
      part_number: editForm.part_number.trim(),
      description: editForm.description.trim() || null,
      classification_type: editForm.classification_type || null,
      default_location: editForm.default_location.trim() || null,
      notes: editForm.notes.trim() || null,
    });

    await loadPart();
    setIsEditing(false);
  }

  function handleCancel() {
    if (part) {
      setEditForm({
        part_number: part.part_number,
        description: part.description || '',
        classification_type: part.classification_type || '',
        default_location: part.default_location || '',
        notes: part.notes || '',
      });
    }
    setIsEditing(false);
  }

  if (loading) {
    return (
      <Dialog open={open} onOpenChange={onClose}>
        <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto">
          <div className="py-8 text-center">
            <p className="text-muted-foreground">Loading part details...</p>
          </div>
        </DialogContent>
      </Dialog>
    );
  }

  if (!part) {
    return (
      <Dialog open={open} onOpenChange={onClose}>
        <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto">
          <div className="py-8 text-center">
            <p className="text-muted-foreground">Part not found</p>
          </div>
        </DialogContent>
      </Dialog>
    );
  }

  const isAssembly = part.classification_type === 'assembly';
  const isModified = part.classification_type === 'modified';

  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="max-w-5xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center justify-between">
            <span>Part Details</span>
            {!isEditing ? (
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsEditing(true)}
              >
                <Edit2 className="mr-2 h-4 w-4" />
                Edit
              </Button>
            ) : (
              <div className="flex gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleCancel}
                >
                  <X className="mr-2 h-4 w-4" />
                  Cancel
                </Button>
                <Button
                  size="sm"
                  onClick={handleSave}
                  disabled={!editForm.part_number.trim()}
                >
                  <Save className="mr-2 h-4 w-4" />
                  Save
                </Button>
              </div>
            )}
          </DialogTitle>
        </DialogHeader>

        <div className="space-y-6">
          {/* Part Information Card */}
          <Card>
            <CardHeader>
              <CardTitle>Part Information</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {isEditing ? (
                <>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                      <Label htmlFor="edit_part_number">Part Number *</Label>
                      <Input
                        id="edit_part_number"
                        value={editForm.part_number}
                        onChange={(e) =>
                          setEditForm({ ...editForm, part_number: e.target.value })
                        }
                      />
                    </div>
                    <div className="space-y-2">
                      <Label htmlFor="edit_classification">Classification</Label>
                      <Select
                        value={editForm.classification_type}
                        onValueChange={(value) =>
                          setEditForm({ ...editForm, classification_type: value as ClassificationType })
                        }
                      >
                        <SelectTrigger>
                          <SelectValue placeholder="Select classification" />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="purchased">Purchased</SelectItem>
                          <SelectItem value="manufactured">Manufactured</SelectItem>
                          <SelectItem value="assembly">Assembly</SelectItem>
                          <SelectItem value="modified">Modified</SelectItem>
                        </SelectContent>
                      </Select>
                    </div>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="edit_description">Description</Label>
                    <Input
                      id="edit_description"
                      value={editForm.description}
                      onChange={(e) =>
                        setEditForm({ ...editForm, description: e.target.value })
                      }
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="edit_location">Default Location</Label>
                    <Input
                      id="edit_location"
                      value={editForm.default_location}
                      onChange={(e) =>
                        setEditForm({ ...editForm, default_location: e.target.value })
                      }
                    />
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="edit_notes">Notes</Label>
                    <Textarea
                      id="edit_notes"
                      value={editForm.notes}
                      onChange={(e) =>
                        setEditForm({ ...editForm, notes: e.target.value })
                      }
                    />
                  </div>
                </>
              ) : (
                <>
                  <div className="flex items-center gap-3">
                    <span className="text-2xl font-bold font-mono">{part.part_number}</span>
                    {part.classification_type && (
                      <Badge className={getClassificationColor(part.classification_type)}>
                        {part.classification_type}
                      </Badge>
                    )}
                  </div>
                  {part.description && (
                    <div>
                      <span className="text-sm text-muted-foreground">Description: </span>
                      <span>{part.description}</span>
                    </div>
                  )}
                  {part.default_location && (
                    <div>
                      <span className="text-sm text-muted-foreground">Location: </span>
                      <span className="font-medium">📍 {part.default_location}</span>
                    </div>
                  )}
                  {part.notes && (
                    <div>
                      <span className="text-sm text-muted-foreground">Notes: </span>
                      <span>{part.notes}</span>
                    </div>
                  )}
                </>
              )}
            </CardContent>
          </Card>

          {/* Base Part (for modified parts) */}
          {isModified && part.base_part && (
            <Card>
              <CardHeader>
                <CardTitle>Based On</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="flex items-center gap-2">
                  <Package className="h-4 w-4 text-muted-foreground" />
                  <span className="font-mono font-medium">{part.base_part.part_number}</span>
                  <ArrowRight className="h-4 w-4 text-muted-foreground" />
                  <span className="font-mono font-medium">{part.part_number}</span>
                  {part.base_part.description && (
                    <span className="text-sm text-muted-foreground ml-2">
                      ({part.base_part.description})
                    </span>
                  )}
                </div>
              </CardContent>
            </Card>
          )}

          {/* Modification Chain */}
          {(isModified || (part.modifications && part.modifications.length > 0)) && (
            <ModificationChain partId={part.id} />
          )}

          {/* BOM (for assemblies) */}
          {isAssembly && (
            <BOMEditor partId={part.id} onUpdate={loadPart} />
          )}

          {/* Where Used */}
          {part.used_in && part.used_in.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle>Where Used ({part.used_in.length})</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-2">
                  {part.used_in.map((rel) => (
                    <div
                      key={rel.id}
                      className="flex items-center justify-between p-2 border rounded"
                    >
                      <div className="flex items-center gap-3">
                        <Package className="h-4 w-4 text-muted-foreground" />
                        <div>
                          <div className="font-mono font-medium">{rel.part.part_number}</div>
                          {rel.part.description && (
                            <div className="text-sm text-muted-foreground">
                              {rel.part.description}
                            </div>
                          )}
                        </div>
                      </div>
                      <div className="text-sm text-muted-foreground">
                        Qty: {rel.quantity}
                        {rel.reference_designator && (
                          <span className="ml-2">({rel.reference_designator})</span>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </DialogContent>
    </Dialog>
  );
}
